[package]
name = "deka_compiler_wasm"
version.workspace = true
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bumpalo = "3"
serde = { workspace = true }
serde_json = { workspace = true }
deka_js = { path = "../deka_js", default-features = false }
modules_php = { path = "../modules_php", default-features = false, features = ["compiler"] }
deka-fmt = { path = "../deka-fmt" }
deka-validation = { path = "../deka-validation", default-features = false }
