use bundler::{BuildOptions, VirtualSource, bundle_virtual_entry, optimize_emitted_module};
use core::{CommandSpec, Context, ParamSpec, Registry};
use phpx_js::{compile_phpx_source_to_js, parse_source_module_meta};
use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::Arc;

const GENERATED_MARKER: &str = "// Generated by deka transpile. Do not edit manually.\n";

const COMMAND: CommandSpec = CommandSpec {
    name: "transpile",
    category: "project",
    summary: "emit V8-target JavaScript from a .ds file or directory",
    aliases: &[],
    subcommands: &[],
    handler: cmd,
};

pub fn register(registry: &mut Registry) {
    registry.add_command(COMMAND);
    registry.add_flag(core::FlagSpec {
        name: "--preserve",
        aliases: &[],
        description: "preserve a directory's module tree (default for directories)",
    });
    registry.add_flag(core::FlagSpec {
        name: "--bundle",
        aliases: &[],
        description: "emit one resolved JavaScript module graph",
    });
    registry.add_flag(core::FlagSpec {
        name: "--treeshake",
        aliases: &[],
        description: "apply the existing JavaScript optimization path to emitted modules",
    });
    registry.add_param(ParamSpec {
        name: "--out",
        description: "output .js file (file/bundle) or output directory (preserve)",
    });
}

pub fn cmd(context: &Context) {
    if context.args.flags.get("--help").copied().unwrap_or(false)
        || context.args.flags.get("-H").copied().unwrap_or(false)
        || context.args.flags.get("help").copied().unwrap_or(false)
    {
        stdio::raw(usage());
        return;
    }
    if let Err(err) = run(context) {
        stdio::error("transpile", &err);
        std::process::exit(1);
    }
}

fn run(context: &Context) -> Result<(), String> {
    let input = context
        .args
        .positionals
        .first()
        .ok_or_else(|| usage().to_string())?;
    if context.args.positionals.len() != 1 {
        return Err(usage().to_string());
    }
    let input = PathBuf::from(input);
    let mode = TranspileMode::from_context(context, &input)?;
    let output = context.args.params.get("--out").map(PathBuf::from);
    let treeshake = context
        .args
        .flags
        .get("--treeshake")
        .copied()
        .unwrap_or(false);

    match (input.is_file(), input.is_dir()) {
        (true, _) => transpile_file(&input, output.as_deref(), mode, treeshake),
        (_, true) => transpile_directory(&input, output.as_deref(), mode, treeshake),
        _ => Err(format!("input path does not exist: {}", input.display())),
    }
}

fn usage() -> &'static str {
    "usage: deka transpile <file-or-directory> [--preserve|--bundle] [--treeshake] [--out <path>]\n\nModes:\n  file: writes adjacent <name>.js by default; --out selects the output file\n  directory: --preserve is the default and mirrors .ds paths as .js paths\n  directory --bundle: requires --out <file.js> and emits one resolved graph\n  --treeshake: applies the existing JavaScript optimization path in either mode\n\nExamples:\n  deka transpile app/main.ds\n  deka transpile app --preserve --out generated\n  deka transpile app --bundle --out dist/app.js --treeshake"
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum TranspileMode {
    Preserve,
    Bundle,
}

impl TranspileMode {
    fn from_context(context: &Context, input: &Path) -> Result<Self, String> {
        let preserve = context
            .args
            .flags
            .get("--preserve")
            .copied()
            .unwrap_or(false);
        let bundle = context.args.flags.get("--bundle").copied().unwrap_or(false);
        if preserve && bundle {
            return Err("--preserve and --bundle cannot be used together".to_string());
        }
        if bundle {
            Ok(Self::Bundle)
        } else if input.is_dir() || preserve {
            Ok(Self::Preserve)
        } else {
            Ok(Self::Preserve)
        }
    }
}

fn transpile_file(
    input: &Path,
    out: Option<&Path>,
    mode: TranspileMode,
    treeshake: bool,
) -> Result<(), String> {
    require_ds(input)?;
    let output = out
        .map(PathBuf::from)
        .unwrap_or_else(|| input.with_extension("js"));
    if output == input {
        return Err("output path must differ from the .ds input path".to_string());
    }
    let mappings = vec![(input.to_path_buf(), output.clone())];
    preflight_outputs(&mappings)?;
    let js = if mode == TranspileMode::Bundle {
        build_bundle(input, treeshake)?
    } else {
        build_module(input, &output, treeshake)?
    };
    commit_outputs(vec![OutputPlan {
        output: output.clone(),
        js,
    }])?;
    stdio::success(&format!(
        "transpiled {} -> {}",
        input.display(),
        output.display()
    ));
    Ok(())
}

fn transpile_directory(
    input: &Path,
    out: Option<&Path>,
    mode: TranspileMode,
    treeshake: bool,
) -> Result<(), String> {
    let sources = collect_ds_sources(input)?;
    if sources.is_empty() {
        return Err(format!("no .ds files found under {}", input.display()));
    }
    match mode {
        TranspileMode::Bundle => {
            let output = out.ok_or_else(|| {
                "directory --bundle requires --out <file.js> so the bundle target is unambiguous"
                    .to_string()
            })?;
            if output.is_dir() || output.extension().and_then(|ext| ext.to_str()) != Some("js") {
                return Err("directory --bundle --out must name a .js file".to_string());
            }
            let entry = directory_entry(input, &sources)?;
            preflight_outputs(&[(entry.clone(), output.to_path_buf())])?;
            let js = build_bundle(&entry, treeshake)?;
            commit_outputs(vec![OutputPlan {
                output: output.to_path_buf(),
                js,
            }])?;
            stdio::success(&format!(
                "transpiled {} -> {}",
                input.display(),
                output.display()
            ));
        }
        TranspileMode::Preserve => {
            let output_root = out
                .map(PathBuf::from)
                .unwrap_or_else(|| input.to_path_buf());
            if output_root.extension().is_some() {
                return Err("directory --preserve --out must name a directory".to_string());
            }
            let mappings = sources
                .iter()
                .map(|source| {
                    source
                        .strip_prefix(input)
                        .map(|rel| (source.clone(), output_root.join(rel).with_extension("js")))
                        .map_err(|_| "failed to preserve source tree".to_string())
                })
                .collect::<Result<Vec<_>, _>>()?;
            preflight_outputs(&mappings)?;
            let plans = mappings
                .iter()
                .map(|(source, output)| {
                    build_module(source, output, treeshake).map(|js| OutputPlan {
                        output: output.clone(),
                        js,
                    })
                })
                .collect::<Result<Vec<_>, _>>()?;
            commit_outputs(plans)?;
            stdio::success(&format!(
                "transpiled {} -> {}",
                input.display(),
                output_root.display()
            ));
        }
    }
    Ok(())
}

fn directory_entry(root: &Path, sources: &[PathBuf]) -> Result<PathBuf, String> {
    for name in ["main.ds", "index.ds", "app.ds"] {
        let candidate = root.join(name);
        if candidate.is_file() {
            return Ok(candidate);
        }
    }
    if sources.len() == 1 {
        return Ok(sources[0].clone());
    }
    Err(format!(
        "directory --bundle needs an entry file (main.ds, index.ds, or app.ds) under {}",
        root.display()
    ))
}

fn build_module(input: &Path, output: &Path, treeshake: bool) -> Result<String, String> {
    let mut js = compile_source(input)?;
    js = rewrite_relative_ds_imports(js);
    if treeshake {
        js = optimize_emitted_module(&js, output)?;
    }
    Ok(js)
}

fn build_bundle(input: &Path, treeshake: bool) -> Result<String, String> {
    let entry = fs::canonicalize(input)
        .map_err(|err| format!("failed to resolve {}: {err}", input.display()))?;
    let project_root = entry.parent().unwrap_or(Path::new(".")).to_path_buf();
    let entry_source = compile_source(&entry)?;
    let provider = Arc::new(DsSourceProvider {
        entry: entry.clone(),
        entry_source,
    });
    bundle_virtual_entry(
        &entry,
        BuildOptions {
            project_root,
            minify: treeshake,
            iife: false,
            stdlib_path: None,
        },
        provider,
    )
}

fn compile_source(input: &Path) -> Result<String, String> {
    require_ds(input)?;
    let source = fs::read_to_string(input)
        .map_err(|err| format!("failed to read {}: {err}", input.display()))?;
    let input_name = input
        .to_str()
        .ok_or_else(|| format!("input path is not valid UTF-8: {}", input.display()))?;
    let meta = parse_source_module_meta(&source);
    // The existing module validator owns package imports but predates the
    // runtime resolver's relative .ds support. Keep relative imports in the
    // emitter metadata while excluding only those frontmatter declarations
    // from package validation; the bundler/runtime resolves them as files.
    let validation_source = mask_relative_frontmatter_imports(&source);
    compile_phpx_source_to_js(&validation_source, input_name, meta)
}

fn mask_relative_frontmatter_imports(source: &str) -> String {
    let mut in_frontmatter = false;
    let mut delimiters = 0;
    source
        .lines()
        .map(|line| {
            if line.trim() == "---" {
                delimiters += 1;
                in_frontmatter = delimiters == 1;
                return line.to_string();
            }
            if delimiters == 1
                && in_frontmatter
                && line.trim_start().starts_with("import ")
                && (line.contains("from './")
                    || line.contains("from \"./")
                    || line.contains("from '../")
                    || line.contains("from \"../"))
            {
                "".to_string()
            } else {
                line.to_string()
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

struct DsSourceProvider {
    entry: PathBuf,
    entry_source: String,
}

impl VirtualSource for DsSourceProvider {
    fn load_virtual(&self, path: &Path) -> Result<Option<String>, String> {
        if path == self.entry {
            return Ok(Some(self.entry_source.clone()));
        }
        if !is_ds(path) {
            return Ok(None);
        }
        compile_source(path).map(Some)
    }
}

fn rewrite_relative_ds_imports(mut js: String) -> String {
    // The emitter deliberately preserves source module specifiers. The CLI's
    // output layout changes only relative .ds targets to their emitted .js peers.
    for quote in ['\'', '"'] {
        let needle = format!("from {quote}");
        let mut cursor = 0;
        while let Some(found) = js[cursor..].find(&needle) {
            let start = cursor + found + needle.len();
            let Some(end) = js[start..].find(quote) else {
                break;
            };
            let end = start + end;
            let specifier = &js[start..end];
            if (specifier.starts_with("./") || specifier.starts_with("../"))
                && specifier.ends_with(".ds")
            {
                js.replace_range(end - 3..end, ".js");
                cursor = end - 1;
            } else {
                cursor = end + 1;
            }
        }
    }
    js
}

fn is_generated_output(path: &Path) -> Result<bool, String> {
    let source = fs::read_to_string(path)
        .map_err(|err| format!("failed to read existing output {}: {err}", path.display()))?;
    Ok(source.starts_with(GENERATED_MARKER))
}

fn preflight_outputs(mappings: &[(PathBuf, PathBuf)]) -> Result<(), String> {
    let source_set = mappings
        .iter()
        .map(|(source, _)| source)
        .collect::<BTreeSet<_>>();
    let mut seen = BTreeSet::new();
    for (_, output) in mappings {
        if source_set.contains(output) || !seen.insert(output) {
            return Err(format!("output collision at {}", output.display()));
        }
        if output.is_dir() {
            return Err(format!(
                "output collision: {} is a directory",
                output.display()
            ));
        }
        if output.exists() && !is_generated_output(output)? {
            return Err(format!(
                "output collision: {} already exists and was not generated by deka transpile",
                output.display()
            ));
        }
    }
    Ok(())
}

struct OutputPlan {
    output: PathBuf,
    js: String,
}

struct StagedOutput {
    output: PathBuf,
    staged: PathBuf,
}

struct CommittedOutput {
    output: PathBuf,
    backup: Option<PathBuf>,
}

fn commit_outputs(plans: Vec<OutputPlan>) -> Result<(), String> {
    let mut staged = Vec::with_capacity(plans.len());
    for (index, plan) in plans.iter().enumerate() {
        if let Some(parent) = plan.output.parent() {
            fs::create_dir_all(parent)
                .map_err(|err| format!("failed to create {}: {err}", parent.display()))?;
        }
        let temporary = temporary_path(&plan.output, index, "new");
        let contents = format!("{GENERATED_MARKER}{}", plan.js);
        if let Err(err) = fs::OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&temporary)
            .and_then(|mut file| std::io::Write::write_all(&mut file, contents.as_bytes()))
        {
            cleanup_staged(&staged);
            return Err(format!("failed to stage {}: {err}", plan.output.display()));
        }
        staged.push(StagedOutput {
            output: plan.output.clone(),
            staged: temporary,
        });
    }

    let mut committed = Vec::with_capacity(staged.len());
    for (index, staged_output) in staged.iter().enumerate() {
        let backup = if staged_output.output.exists() {
            let backup = temporary_path(&staged_output.output, index, "backup");
            if backup.exists() {
                rollback_outputs(&committed, &staged);
                return Err(format!(
                    "failed to stage existing {}: temporary path {} already exists",
                    staged_output.output.display(),
                    backup.display()
                ));
            }
            if let Err(err) = fs::rename(&staged_output.output, &backup) {
                rollback_outputs(&committed, &staged);
                return Err(format!(
                    "failed to stage existing {}: {err}",
                    staged_output.output.display()
                ));
            }
            Some(backup)
        } else {
            None
        };
        if let Err(err) = fs::rename(&staged_output.staged, &staged_output.output) {
            let current = CommittedOutput {
                output: staged_output.output.clone(),
                backup,
            };
            rollback_outputs(std::slice::from_ref(&current), &staged);
            rollback_outputs(&committed, &staged);
            return Err(format!(
                "failed to commit {}: {err}",
                staged_output.output.display()
            ));
        }
        committed.push(CommittedOutput {
            output: staged_output.output.clone(),
            backup,
        });
    }
    for committed_output in committed {
        if let Some(backup) = committed_output.backup {
            let _ = fs::remove_file(backup);
        }
    }
    Ok(())
}

fn temporary_path(output: &Path, index: usize, kind: &str) -> PathBuf {
    let name = output.file_name().unwrap_or_default().to_string_lossy();
    output.with_file_name(format!(
        ".{name}.deka-transpile-{}-{index}.{kind}",
        std::process::id()
    ))
}

fn cleanup_staged(staged: &[StagedOutput]) {
    for staged_output in staged {
        let _ = fs::remove_file(&staged_output.staged);
    }
}

fn rollback_outputs(committed: &[CommittedOutput], staged: &[StagedOutput]) {
    for committed_output in committed.iter().rev() {
        let _ = fs::remove_file(&committed_output.output);
        if let Some(backup) = &committed_output.backup {
            let _ = fs::rename(backup, &committed_output.output);
        }
    }
    cleanup_staged(staged);
}

fn collect_ds_sources(root: &Path) -> Result<Vec<PathBuf>, String> {
    let mut out = Vec::new();
    collect_ds_sources_inner(root, &mut out)?;
    out.sort();
    Ok(out)
}

fn collect_ds_sources_inner(dir: &Path, out: &mut Vec<PathBuf>) -> Result<(), String> {
    let mut entries = fs::read_dir(dir)
        .map_err(|err| format!("failed to read {}: {err}", dir.display()))?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|err| format!("failed to read {}: {err}", dir.display()))?;
    entries.sort_by_key(|entry| entry.file_name());
    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            collect_ds_sources_inner(&path, out)?;
        } else if is_ds(&path) {
            out.push(path);
        }
    }
    Ok(())
}

fn require_ds(path: &Path) -> Result<(), String> {
    if is_ds(path) {
        Ok(())
    } else {
        Err(format!(
            "DekaScript uses .ds only; cannot transpile {}",
            path.display()
        ))
    }
}

fn is_ds(path: &Path) -> bool {
    path.extension().and_then(|ext| ext.to_str()) == Some("ds")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::process::Command;

    fn write(path: &Path, source: &str) {
        fs::create_dir_all(path.parent().expect("parent")).expect("mkdir");
        fs::write(path, source).expect("write fixture");
    }

    #[test]
    fn file_output_is_adjacent_and_executes_when_node_is_available() {
        let temp = tempfile::tempdir().expect("tempdir");
        let input = temp.path().join("answer.ds");
        write(&input, "export const answer = 42;\n");
        transpile_file(&input, None, TranspileMode::Preserve, false).expect("transpile");
        let output = input.with_extension("js");
        let emitted = fs::read_to_string(&output).expect("output");
        assert!(emitted.starts_with(GENERATED_MARKER));
        assert!(emitted.contains("answer"));
        if Command::new("node").arg("--version").output().is_ok() {
            write(&temp.path().join("package.json"), "{\"type\":\"module\"}\n");
            let check = Command::new("node")
                .args([
                    "--input-type=module",
                    "-e",
                    "import('./answer.js').then(m => { if (m.answer !== 42) process.exit(1); })",
                ])
                .current_dir(temp.path())
                .output()
                .expect("run node");
            assert!(
                check.status.success(),
                "{}",
                String::from_utf8_lossy(&check.stderr)
            );
        }
    }

    #[test]
    fn preserve_mirrors_tree_and_rewrites_relative_ds_imports() {
        let temp = tempfile::tempdir().expect("tempdir");
        let root = temp.path().join("src");
        write(
            &root.join("nested/math.ds"),
            include_str!("../../tests/fixtures/transpile/tree/nested/math.ds"),
        );
        write(
            &root.join("main.ds"),
            include_str!("../../tests/fixtures/transpile/tree/main.ds"),
        );
        let out = temp.path().join("generated");
        transpile_directory(&root, Some(&out), TranspileMode::Preserve, false).expect("transpile");
        assert!(out.join("nested/math.js").is_file());
        assert!(
            fs::read_to_string(out.join("main.js"))
                .expect("main")
                .contains("./nested/math.js")
        );
    }

    #[test]
    fn bundle_requires_explicit_file_for_directory_and_treeshakes() {
        let temp = tempfile::tempdir().expect("tempdir");
        let root = temp.path().join("src");
        write(
            &root.join("dep.ds"),
            include_str!("../../tests/fixtures/transpile/bundle/dep.ds"),
        );
        write(
            &root.join("main.ds"),
            include_str!("../../tests/fixtures/transpile/bundle/main.ds"),
        );
        let err =
            transpile_directory(&root, None, TranspileMode::Bundle, true).expect_err("needs out");
        assert!(err.contains("requires --out"));
        let out = temp.path().join("bundle.js");
        transpile_directory(&root, Some(&out), TranspileMode::Bundle, true).expect("bundle");
        let emitted = fs::read_to_string(out).expect("bundle output");
        assert!(emitted.starts_with(GENERATED_MARKER));
        assert!(emitted.contains("answer"), "{emitted}");
        assert!(!emitted.contains("from './dep.ds'"), "{emitted}");
        assert!(!emitted.contains("unused"), "{emitted}");
    }

    #[test]
    fn rejects_invalid_input_flags_and_unowned_output_collision() {
        let temp = tempfile::tempdir().expect("tempdir");
        let txt = temp.path().join("bad.txt");
        write(&txt, "nope\n");
        assert!(transpile_file(&txt, None, TranspileMode::Preserve, false).is_err());
        let input = temp.path().join("main.ds");
        let output = temp.path().join("main.js");
        write(&input, "export const value = 1;\n");
        write(&output, "customer file\n");
        assert!(
            transpile_file(&input, Some(&output), TranspileMode::Preserve, false)
                .expect_err("collision")
                .contains("output collision")
        );
    }

    #[test]
    fn directory_collision_preflight_leaves_all_declared_outputs_untouched() {
        let temp = tempfile::tempdir().expect("tempdir");
        let root = temp.path().join("src");
        write(&root.join("main.ds"), "export const main = 1;\n");
        write(&root.join("nested/math.ds"), "export const math = 2;\n");
        let protected = root.join("nested/math.js");
        write(&protected, "customer file\n");

        let error = transpile_directory(&root, None, TranspileMode::Preserve, false)
            .expect_err("preflight collision");

        assert!(error.contains("output collision"));
        assert!(
            !root.join("main.js").exists(),
            "a sibling output was written before collision validation"
        );
        assert_eq!(
            fs::read_to_string(protected).expect("protected output"),
            "customer file\n"
        );
    }

    #[test]
    fn help_documents_modes_defaults_outputs_and_examples() {
        let help = usage();
        for expected in ["Modes:", "by default", "--out", "Examples:", "--treeshake"] {
            assert!(help.contains(expected), "missing {expected} from {help}");
        }
    }

    #[test]
    fn masks_only_relative_frontmatter_imports_for_package_validation() {
        let source = "---\nimport { local } from './local.ds'\nimport { pkg } from 'pkg'\n---\nexport const answer = local;\n";
        let masked = mask_relative_frontmatter_imports(source);
        assert!(!masked.contains("./local.ds"));
        assert!(masked.contains("from 'pkg'"));
    }
}
