use std::fs;
use std::process::Command;
#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;

fn cli_bin() -> &'static str {
    env!("CARGO_BIN_EXE_cli")
}

fn private_tempdir() -> tempfile::TempDir {
    let temp = tempfile::Builder::new()
        .prefix(".deka-transpile-cli-test-")
        .tempdir_in(".")
        .expect("private tempdir");
    #[cfg(unix)]
    fs::set_permissions(temp.path(), fs::Permissions::from_mode(0o700))
        .expect("private tempdir permissions");
    temp
}

#[test]
fn transpile_command_emits_adjacent_v8_input() {
    let temp = private_tempdir();
    let source = temp.path().join("answer.ds");
    fs::write(&source, "export const answer = 42;\n").expect("source fixture");

    let output = Command::new(cli_bin())
        .arg("transpile")
        .arg(&source)
        .output()
        .expect("run transpile");
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );

    let emitted = fs::read_to_string(source.with_extension("js")).expect("emitted JavaScript");
    assert!(
        emitted.starts_with("// Generated by dsc transpile.")
            || emitted.starts_with("// Generated by deka transpile."),
        "{emitted}"
    );
    assert!(emitted.contains("export const answer = 42;"), "{emitted}");
}

#[test]
fn transpile_help_describes_output_modes() {
    let output = Command::new(cli_bin())
        .args(["transpile", "--help"])
        .output()
        .expect("run transpile help");
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );
    let text = format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    for expected in ["--preserve", "--bundle", "--treeshake", "--client", "Examples:"] {
        assert!(text.contains(expected), "missing {expected}: {text}");
    }
}
