use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

pub fn build_stdlib_prelude(project_root: &Path) -> Result<String, String> {
    let stdlib_path = project_root.join("php_modules").join("stdlib.json");
    let raw = fs::read_to_string(&stdlib_path)
        .map_err(|err| format!("failed to read {}: {}", stdlib_path.display(), err))?;
    let entries: Vec<String> = serde_json::from_str(&raw)
        .map_err(|err| format!("failed to parse {}: {}", stdlib_path.display(), err))?;

    let modules_dir = project_root.join("php_modules");
    let mut modules = BTreeSet::new();
    for entry in entries {
        if let Some(prefix) = entry.strip_suffix("/*") {
            let dir = modules_dir.join(prefix);
            let read_dir = fs::read_dir(&dir)
                .map_err(|err| format!("failed to read {}: {}", dir.display(), err))?;
            for item in read_dir {
                let item =
                    item.map_err(|err| format!("failed to read {}: {}", dir.display(), err))?;
                let path = item.path();
                let ext = path.extension().and_then(|e| e.to_str()).unwrap_or("");
                if ext != "phpx" && ext != "php" {
                    continue;
                }
                if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                    modules.insert(format!("{}/{}", prefix, stem));
                }
            }
        } else {
            modules.insert(entry);
        }
    }

    let mut imports = Vec::new();
    let mut binds = Vec::new();
    for (idx, spec) in modules.iter().enumerate() {
        let var = format!("__deka_mod_{}", idx);
        imports.push(format!("import * as {} from '{}';", var, spec));
        binds.push(var);
    }

    let mut prelude = String::new();
    prelude.push_str("// Generated by deka JS prelude. Do not edit manually.\n");
    prelude.push_str(&imports.join("\n"));
    prelude.push('\n');
    prelude.push_str("const __dekaExportToGlobal = (mod) => {\n");
    prelude.push_str("  if (!mod) return;\n");
    prelude.push_str("  for (const [key, value] of Object.entries(mod)) {\n");
    prelude.push_str("    if (key === 'default' || key === '__esModule') continue;\n");
    prelude.push_str("    globalThis[key] = value;\n");
    prelude.push_str("  }\n");
    prelude.push_str("};\n");
    // Use ??= (nullish coalescing assignment) instead of if(!x){x=y}
    // to avoid SWC compress bug that incorrectly transforms the if pattern.
    prelude.push_str("globalThis.panic ??= (msg) => { throw new Error(String(msg)); };\n");
    // function_exists / class_exists are compile-time rewrites in try_rewrite_builtin.
    // No globalThis polyfill emitted here.
    prelude.push_str("globalThis.class_alias ??= () => false;\n");
    // PHP filesystem builtins — polyfilled using __dekaFs (Deno/Node FS adapter injected by the runtime).
    // Capability-gated FS: __dekaFs is the runtime-injected adapter that respects
    // deka.json security manifest. NEVER fall through to raw Deno.* ops — that would
    // bypass the sandbox and let any tenant read /etc/passwd via is_file(...).
    prelude.push_str("globalThis.__phpx_stat ??= (p) => { try { if (typeof __dekaFs !== 'undefined' && __dekaFs && typeof __dekaFs.statSync === 'function') return __dekaFs.statSync(String(p)); } catch(_) {} return null; };\n");
    prelude.push_str("globalThis.is_file ??= (p) => { const s = globalThis.__phpx_stat(p); if (!s) return false; return typeof s.isFile === 'function' ? s.isFile() : !!s.isFile; };\n");
    prelude.push_str("globalThis.is_dir ??= (p) => { const s = globalThis.__phpx_stat(p); if (!s) return false; return typeof s.isDirectory === 'function' ? s.isDirectory() : !!s.isDirectory; };\n");
    prelude.push_str("globalThis.mkdir ??= (p, mode, recursive) => { try { const fs = typeof __dekaFs !== 'undefined' ? __dekaFs : null; if (fs && typeof fs.mkdirSync === 'function') { fs.mkdirSync(String(p), { recursive: !!recursive }); return true; } } catch(_) {} return false; };\n");
    prelude.push_str("globalThis.file ??= (p) => { try { const fs = typeof __dekaFs !== 'undefined' ? __dekaFs : null; if (!fs || typeof fs.readFileSync !== 'function') return false; const text = fs.readFileSync(String(p), 'utf8'); if (text === null) return false; return text.split('\\n').map((l, i, a) => i < a.length - 1 ? l + '\\n' : l).filter((_, i, a) => !(i === a.length - 1 && a[i] === '')); } catch(_) { return false; } };\n");
    prelude.push_str("if (!globalThis.__dekaGlobalsInstalled) {\n");
    prelude.push_str("  globalThis.__dekaGlobalsInstalled = true;\n");
    for var in &binds {
        prelude.push_str(&format!("  __dekaExportToGlobal({});\n", var));
    }
    prelude.push_str("}\n");

    Ok(prelude)
}
