[package]
name = "deka-native"
version.workspace = true
edition = "2024"
license = "Apache-2.0"
publish = false

[features]
default = []
gpu = ["deka_native_ui/gpu"]
runtime-shaders = ["gpu", "deka_native_ui/runtime-shaders"]

[dependencies]
deka_native_ui = { path = "../deka_native_ui", features = ["program"] }
deka_native_ir = { git = "https://github.com/dekaruntime/dsc", rev = "f3524ef87ab312d2fa7195d42d6ec14cdc0f1384", features = ["program"] }
serde_json = "1.0"

[dev-dependencies]
deka_native_compile = { git = "https://github.com/dekaruntime/dsc", rev = "f3524ef87ab312d2fa7195d42d6ec14cdc0f1384" }
