[package]
name = "cli"
version.workspace = true
edition = "2024"

[features]
default = ["native"]
native = [
  "dep:compile",
  "dep:pm",
  "dep:runtime",
  "dep:introspect",
  "dep:tokio",
  "dep:postgres",
  "dep:deka_host",
  "dep:bundler",
  "dep:rusqlite",
]
lsp = ["dep:dekascript_lsp"]

[dependencies]
runtime = { path = "../runtime", optional = true }
runtime_core = { path = "../runtime_core" }
compile = { path = "../compile", optional = true }
core = { path ="../core" }
stdio = { path = "../stdio" }
introspect = { path = "../introspect", optional = true }
wasm_cli = { path = "../wasm_cli" }
pm = { workspace = true, optional = true }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1.35", features = ["rt-multi-thread", "net", "io-util"], optional = true }
postgres = { version = "0.19", optional = true }
dekascript_lsp = { path = "../deka_lsp", optional = true }
deka_host = { path = "../deka_host", optional = true, default-features = false, features = ["runtime"] }
rusqlite = { version = "0.32", optional = true }
sha2 = "0.10"
ctrlc = "3"
deno_task_shell = "0.29.0"
glob = "0.3.1"
serde_yaml = "0.9"
bundler = { path = "../bundler", optional = true }
deka_ui = { path = "../deka_ui" }
libc = "0.2"
tempfile = "3.23.0"

[dev-dependencies]
tempfile = "3.23.0"
flate2 = "1.0"
base64 = "0.22"
