[package]
name = "deka-task"
version.workspace = true
edition = "2024"

[dependencies]
deka-cli-core = { version = "0.5.0", default-features = false, features = ["registry"] }
stdio = "0.4.0"
serde_json = "1.0"
deno_task_shell = "0.29.0"
glob = "0.3.1"
tokio = { version = "1.35", features = ["rt"] }

[dev-dependencies]
tempfile = "3.23.0"
