[package]
name = "gild-storm"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "gild-storm"
path = "src/main.rs"

[dependencies]
anyhow = "1"
chrono = { workspace = true }
clap = { version = "4.5", features = ["derive"] }
ctrlc = "3"
humantime = "2"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "rustls-tls"] }
serde = { workspace = true, features = ["derive"] }
serde_yaml = "0.9"
