use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use bumpalo::Bump;
use core::Context;
use php_rs::parser::ast::{ClassKind, ClassMember, Name, Stmt, Type as AstType};
use php_rs::parser::lexer::Lexer;
use php_rs::parser::parser::{Parser, ParserMode};
use serde_json::json;
use stdio::{error, log};

use super::migrate::render_init_migration;

pub(super) fn cmd_generate(context: &Context) {
    let cwd = &context.env.cwd;
    let source = match resolve_generate_input(cwd, context.args.positionals.first()) {
        Ok(path) => path,
        Err(message) => {
            error("db generate", &message);
            return;
        }
    };

    let source_text = match fs::read_to_string(&source) {
        Ok(value) => value,
        Err(err) => {
            error(
                "db generate",
                &format!("failed to read model entry {}: {}", source.display(), err),
            );
            return;
        }
    };

    let models = match extract_struct_models(&source_text, source.display().to_string()) {
        Ok(value) => value,
        Err(message) => {
            error("db generate", &message);
            return;
        }
    };
    if models.is_empty() {
        error(
            "db generate",
            &format!(
                "no struct models found in {}. define at least one `struct Name {{ ... }}`",
                source.display()
            ),
        );
        return;
    }

    let generated = match generate_db_artifacts(cwd, &source, &models) {
        Ok(value) => value,
        Err(message) => {
            error("db generate", &message);
            return;
        }
    };

    log(
        "db generate",
        &format!(
            "generated {} files from {} model(s) in {}",
            generated,
            models.len(),
            source.display()
        ),
    );
}

pub(super) fn resolve_generate_input(
    cwd: &Path,
    input: Option<&String>,
) -> Result<PathBuf, String> {
    let raw = input
        .map(String::as_str)
        .filter(|s| !s.trim().is_empty())
        .unwrap_or("types/index.phpx");
    let candidate = if let Some(stripped) = raw.strip_prefix("@/") {
        cwd.join(stripped)
    } else {
        cwd.join(raw)
    };
    resolve_model_entry(&candidate, raw)
}

pub(super) fn resolve_model_entry(candidate: &Path, raw: &str) -> Result<PathBuf, String> {
    if candidate.is_file() {
        if candidate.extension().and_then(|v| v.to_str()) != Some("phpx") {
            return Err(format!("expected a .phpx model entry file, got: {}", raw));
        }
        return Ok(candidate.to_path_buf());
    }

    if candidate.is_dir() {
        let index = candidate.join("index.phpx");
        if index.is_file() {
            return Ok(index);
        }
        return Err(format!(
            "expected model entry file, got directory: {}. tried: {}/index.phpx",
            raw,
            raw.trim_end_matches('/')
        ));
    }

    Err(format!(
        "model input not found: {}. pass a .phpx file or a directory containing index.phpx",
        raw
    ))
}

const GENERATED_HEADER: &str = "/*\n\
 * AUTO-GENERATED FILE - DO NOT EDIT\n\
 * Generated by deka db generate\n\
 * Changes will be overwritten.\n\
 */\n\n";

#[derive(Debug, Clone)]
pub(super) struct ModelDef {
    pub(super) name: String,
    pub(super) fields: Vec<FieldDef>,
}

#[derive(Debug, Clone)]
pub(super) struct FieldDef {
    pub(super) name: String,
    pub(super) ty: String,
    pub(super) annotations: Vec<FieldAnnotationDef>,
}

#[derive(Debug, Clone)]
pub(super) struct FieldAnnotationDef {
    pub(super) name: String,
    pub(super) args: Vec<String>,
}

#[derive(Debug, Clone)]
pub(super) struct RelationSpec {
    pub(super) kind: String,
    pub(super) _model: String,
    pub(super) foreign_key: String,
}

impl FieldDef {
    pub(super) fn annotation(&self, name: &str) -> Option<&FieldAnnotationDef> {
        self.annotations.iter().find(|ann| ann.name == name)
    }

    pub(super) fn has_annotation(&self, name: &str) -> bool {
        self.annotation(name).is_some()
    }

    pub(super) fn mapped_name(&self) -> String {
        self.annotation("map")
            .and_then(|ann| ann.args.first())
            .map(|arg| unquote(arg))
            .filter(|name| !name.is_empty())
            .unwrap_or_else(|| self.name.clone())
    }

    pub(super) fn relation_spec(&self) -> Option<RelationSpec> {
        let ann = self.annotation("relation")?;
        if ann.args.len() != 3 {
            return None;
        }
        let kind = unquote(&ann.args[0]);
        let model = unquote(&ann.args[1]);
        let foreign_key = unquote(&ann.args[2]);
        if kind.is_empty() || model.is_empty() || foreign_key.is_empty() {
            return None;
        }
        if kind != "hasMany" && kind != "belongsTo" && kind != "hasOne" {
            return None;
        }
        Some(RelationSpec {
            kind,
            _model: model,
            foreign_key,
        })
    }
}

pub(super) fn extract_struct_models(
    source: &str,
    file_path: String,
) -> Result<Vec<ModelDef>, String> {
    let arena = Bump::new();
    let mut parser = Parser::new_with_mode(Lexer::new(source.as_bytes()), &arena, ParserMode::Phpx);
    let program = parser.parse_program();
    if !program.errors.is_empty() {
        let rendered = program
            .errors
            .iter()
            .map(|err| err.to_human_readable_with_path(source.as_bytes(), Some(&file_path)))
            .collect::<Vec<_>>()
            .join("\n\n");
        return Err(rendered);
    }

    let mut out = Vec::new();
    collect_struct_models_from_statements(&mut out, program.statements, source.as_bytes());
    Ok(out)
}

fn collect_struct_models_from_statements(
    out: &mut Vec<ModelDef>,
    statements: &[&Stmt<'_>],
    source: &[u8],
) {
    for stmt in statements {
        match stmt {
            Stmt::Class {
                kind,
                name,
                members,
                ..
            } if *kind == ClassKind::Struct => {
                let mut fields = Vec::new();
                for member in *members {
                    if let ClassMember::Property { ty, entries, .. } = member {
                        let Some(field_type) = ty.as_ref() else {
                            continue;
                        };
                        for entry in *entries {
                            let field_name =
                                String::from_utf8_lossy(entry.name.text(source)).to_string();
                            fields.push(FieldDef {
                                name: field_name.trim_start_matches('$').to_string(),
                                ty: render_ast_type(field_type, source),
                                annotations: entry
                                    .annotations
                                    .iter()
                                    .map(|ann| FieldAnnotationDef {
                                        name: String::from_utf8_lossy(ann.name.text(source))
                                            .to_string(),
                                        args: ann
                                            .args
                                            .iter()
                                            .map(|arg| {
                                                String::from_utf8_lossy(arg.span().as_str(source))
                                                    .to_string()
                                            })
                                            .collect(),
                                    })
                                    .collect(),
                            });
                        }
                    }
                }
                out.push(ModelDef {
                    name: String::from_utf8_lossy(name.text(source)).to_string(),
                    fields,
                });
            }
            Stmt::Namespace {
                body: Some(body), ..
            } => {
                collect_struct_models_from_statements(out, body, source);
            }
            _ => {}
        }
    }
}

fn render_name(name: &Name<'_>, source: &[u8]) -> String {
    name.parts
        .iter()
        .map(|part| String::from_utf8_lossy(part.text(source)).to_string())
        .collect::<Vec<_>>()
        .join("\\")
}

fn render_ast_type(ty: &AstType<'_>, source: &[u8]) -> String {
    match ty {
        AstType::Simple(tok) => String::from_utf8_lossy(tok.text(source)).to_string(),
        AstType::Name(name) => render_name(name, source),
        AstType::Union(parts) => parts
            .iter()
            .map(|part| render_ast_type(part, source))
            .collect::<Vec<_>>()
            .join("|"),
        AstType::Intersection(parts) => parts
            .iter()
            .map(|part| render_ast_type(part, source))
            .collect::<Vec<_>>()
            .join("&"),
        AstType::Nullable(inner) => format!("?{}", render_ast_type(inner, source)),
        AstType::ObjectShape(fields) => {
            let rendered = fields
                .iter()
                .map(|field| {
                    let name = String::from_utf8_lossy(field.name.text(source)).to_string();
                    let optional = if field.optional { "?" } else { "" };
                    format!(
                        "{}{}: {}",
                        name,
                        optional,
                        render_ast_type(field.ty, source)
                    )
                })
                .collect::<Vec<_>>()
                .join(", ");
            format!("{{ {} }}", rendered)
        }
        AstType::Applied { base, args } => format!(
            "{}<{}>",
            render_ast_type(base, source),
            args.iter()
                .map(|arg| render_ast_type(arg, source))
                .collect::<Vec<_>>()
                .join(", ")
        ),
        AstType::Option(inner) => format!("Option<{}>", render_ast_type(inner, source)),
    }
}

pub(super) fn generate_db_artifacts(
    cwd: &Path,
    source: &Path,
    models: &[ModelDef],
) -> Result<usize, String> {
    let db_dir = cwd.join("db");
    let generated_dir = db_dir.join(".generated");
    let migrations_dir = db_dir.join("migrations");
    fs::create_dir_all(&generated_dir)
        .map_err(|e| format!("failed to create db/.generated: {}", e))?;
    fs::create_dir_all(&migrations_dir)
        .map_err(|e| format!("failed to create db/migrations: {}", e))?;

    let index_path = db_dir.join("index.phpx");
    let client_path = db_dir.join("client.phpx");
    let meta_path = db_dir.join("meta.phpx");
    let state_path = db_dir.join("_state.json");
    let migration_path = migrations_dir.join("0001_init.sql");
    let schema_path = generated_dir.join("schema.json");

    let index_body = render_index_phpx();
    let client_body = render_client_phpx(models);
    let meta_body = render_meta_phpx(models);
    let state_body = render_state_json(source, models);
    let migration_body = render_init_migration(models);
    let schema_body = render_generated_schema_json(models);

    fs::write(&index_path, index_body)
        .map_err(|e| format!("failed to write {}: {}", index_path.display(), e))?;
    fs::write(&client_path, client_body)
        .map_err(|e| format!("failed to write {}: {}", client_path.display(), e))?;
    fs::write(&meta_path, meta_body)
        .map_err(|e| format!("failed to write {}: {}", meta_path.display(), e))?;
    fs::write(&state_path, state_body)
        .map_err(|e| format!("failed to write {}: {}", state_path.display(), e))?;
    fs::write(&migration_path, migration_body)
        .map_err(|e| format!("failed to write {}: {}", migration_path.display(), e))?;
    fs::write(&schema_path, schema_body)
        .map_err(|e| format!("failed to write {}: {}", schema_path.display(), e))?;

    Ok(6)
}

fn render_index_phpx() -> String {
    format!(
        "{}import {{ connect, close, select, selectMany, selectOne, insert, insertOne, update, updateWhere, deleteQuery, deleteWhere, loadRelation, transaction, eq, ilike, isNull, andWhere, orWhere, asc, desc, limit, offset, createClient }} from '@/db/client'\n\
export {{ connect, close, select, selectMany, selectOne, insert, insertOne, update, updateWhere, deleteQuery, deleteWhere, loadRelation, transaction, eq, ilike, isNull, andWhere, orWhere, asc, desc, limit, offset, createClient }}\n",
        GENERATED_HEADER
    )
}

pub(super) fn render_client_phpx(models: &[ModelDef]) -> String {
    let mut model_map = String::new();
    for model in models {
        model_map.push_str(&format!(
            "        {}: {{ name: '{}' }},\n",
            model.name, model.name
        ));
    }
    let raw = format!(
        "{}import {{ open_handle, close as db_close, query as db_query, exec as db_exec, rows as db_rows, begin as db_begin, commit as db_commit, rollback as db_rollback }} from 'db'\n\
import {{ result_ok, result_err, result_is_ok }} from 'core/result'\n\n\
function quote_ident($name) {{\n\
    return '\"' . str_replace('\"', '\"\"', '' . $name) . '\"'\n\
}}\n\n\
function model_name($model) {{\n\
    if (is_string($model)) {{\n\
        return $model\n\
    }}\n\
    if (is_object($model) && isset($model->name)) {{\n\
        return '' . $model->name\n\
    }}\n\
    if (is_array($model) && array_key_exists('name', $model)) {{\n\
        return '' . $model['name']\n\
    }}\n\
    return null\n\
}}\n\n\
function to_snake_case($name) {{\n\
    $out = ''\n\
    $len = strlen($name)\n\
    for ($i = 0; $i < $len; $i = $i + 1) {{\n\
        $ch = $name[$i]\n\
        $is_upper = ($ch >= 'A' && $ch <= 'Z')\n\
        if ($is_upper && $i > 0) {{\n\
            $prev = $name[$i - 1]\n\
            $prev_lower = ($prev >= 'a' && $prev <= 'z') || ($prev >= '0' && $prev <= '9')\n\
            if ($prev_lower) {{\n\
                $out = $out . '_'\n\
            }}\n\
        }}\n\
        $out = $out . strtolower($ch)\n\
    }}\n\
    return $out\n\
}}\n\n\
function model_table($model) {{\n\
    $name = model_name($model)\n\
    if ($name === null || $name === '') {{\n\
        return null\n\
    }}\n\
    $table = to_snake_case($name)\n\
    if (substr($table, -1) !== 's') {{\n\
        $table = $table . 's'\n\
    }}\n\
    return $table\n\
}}\n\n\
function field_value($obj, $key, $fallback = null) {{\n\
    if (is_array($obj) && array_key_exists($key, $obj)) {{\n\
        return $obj[$key]\n\
    }}\n\
    if (is_object($obj) && isset($obj->{{$key}})) {{\n\
        return $obj->{{$key}}\n\
    }}\n\
    if (isset($obj[$key])) {{\n\
        return $obj[$key]\n\
    }}\n\
    return $fallback\n\
}}\n\n\
function compile_predicate($expr, &$params) {{\n\
    if ($expr === null) {{\n\
        return ''\n\
    }}\n\
    $kind = field_value($expr, 'kind', null)\n\
    if (!is_string($kind) || $kind === '') {{\n\
        return ''\n\
    }}\n\
    if ($kind === 'eq') {{\n\
        $column = field_value($expr, 'column', null)\n\
        if (!is_string($column) || $column === '') {{\n\
            return ''\n\
        }}\n\
        $params[] = field_value($expr, 'value', null)\n\
        return quote_ident($column) . ' = $' . count($params)\n\
    }}\n\
    if ($kind === 'and' || $kind === 'or') {{\n\
        $parts = field_value($expr, 'parts', [])\n\
        $parts_sql = []\n\
        foreach ($parts as $part) {{\n\
            $inner = compile_predicate($part, $params)\n\
            if ($inner !== '') {{\n\
                $parts_sql[] = '(' . $inner . ')'\n\
            }}\n\
        }}\n\
        if (count($parts_sql) === 0) {{\n\
            return ''\n\
        }}\n\
        return implode($kind === 'and' ? ' AND ' : ' OR ', $parts_sql)\n\
    }}\n\
    if ($kind === 'ilike') {{\n\
        $column = field_value($expr, 'column', null)\n\
        if (!is_string($column) || $column === '') {{\n\
            return ''\n\
        }}\n\
        $params[] = field_value($expr, 'value', null)\n\
        return quote_ident($column) . ' ILIKE $' . count($params)\n\
    }}\n\
    if ($kind === 'isNull') {{\n\
        $column = field_value($expr, 'column', null)\n\
        if (!is_string($column) || $column === '') {{\n\
            return ''\n\
        }}\n\
        return quote_ident($column) . ' IS NULL'\n\
    }}\n\
    return ''\n\
}}\n\n\
export function eq($column, $value) {{\n\
    return [ 'kind' => 'eq', 'column' => $column, 'value' => $value ]\n\
}}\n\n\
export function ilike($column, $value) {{\n\
    return [ 'kind' => 'ilike', 'column' => $column, 'value' => $value ]\n\
}}\n\n\
export function isNull($column) {{\n\
    return [ 'kind' => 'isNull', 'column' => $column ]\n\
}}\n\n\
export function andWhere(...$parts) {{\n\
    return [ 'kind' => 'and', 'parts' => $parts ]\n\
}}\n\n\
export function orWhere(...$parts) {{\n\
    return [ 'kind' => 'or', 'parts' => $parts ]\n\
}}\n\n\
export function asc($column) {{\n\
    return [ 'column' => $column, 'dir' => 'ASC' ]\n\
}}\n\n\
export function desc($column) {{\n\
    return [ 'column' => $column, 'dir' => 'DESC' ]\n\
}}\n\n\
export function limit($value) {{\n\
    return (int) $value\n\
}}\n\n\
export function offset($value) {{\n\
    return (int) $value\n\
}}\n\n\
export function connect($driver, $config) {{\n\
    return open_handle($driver, $config)\n\
}}\n\n\
export function close($handle) {{\n\
    return db_close($handle)\n\
}}\n\n\
function normalize_includes($includes) {{\n\
    if ($includes === null) {{\n\
        return []\n\
    }}\n\
    if (is_string($includes) && $includes !== '') {{\n\
        return [$includes]\n\
    }}\n\
    if (is_array($includes)) {{\n\
        return $includes\n\
    }}\n\
    return []\n\
}}\n\n\
function apply_includes_to_row($handle, $meta, $model, $row, $includes) {{\n\
    if (!is_array($row)) {{\n\
        return result_err('include expects row array')\n\
    }}\n\
    $out = $row\n\
    foreach (normalize_includes($includes) as $field) {{\n\
        $loaded = loadRelation($handle, $meta, $model, $row, $field)\n\
        if (!result_is_ok($loaded)) {{\n\
            return $loaded\n\
        }}\n\
        $out[$field] = $loaded->value\n\
    }}\n\
    return result_ok($out)\n\
}}\n\n\
function apply_includes_to_rows($handle, $meta, $model, $rows, $includes) {{\n\
    $fields = normalize_includes($includes)\n\
    if (count($fields) === 0) {{\n\
        return result_ok($rows)\n\
    }}\n\
    $out = []\n\
    foreach ($rows as $row) {{\n\
        $one = apply_includes_to_row($handle, $meta, $model, $row, $fields)\n\
        if (!result_is_ok($one)) {{\n\
            return $one\n\
        }}\n\
        $out[] = $one->value\n\
    }}\n\
    return result_ok($out)\n\
}}\n\n\
export function selectMany($handle, $meta, $model, $where = null, $order = null, $limit = null, $offset = null, $includes = null) {{\n\
    $table = model_table($model)\n\
    if ($table === null) {{\n\
        return result_err('unknown model')\n\
    }}\n\
    $sql = 'SELECT * FROM ' . quote_ident($table)\n\
    $params = []\n\
    $where_sql = compile_predicate($where, $params)\n\
    if ($where_sql !== '') {{\n\
        $sql = $sql . ' WHERE ' . $where_sql\n\
    }}\n\
    if ($order !== null && (is_array($order) || is_object($order)) && field_value($order, 'column', null) !== null) {{\n\
        $dir = 'ASC'\n\
        if (strtoupper('' . field_value($order, 'dir', 'ASC')) === 'DESC') {{\n\
            $dir = 'DESC'\n\
        }}\n\
        $sql = $sql . ' ORDER BY ' . quote_ident('' . field_value($order, 'column', '')) . ' ' . $dir\n\
    }}\n\
    if ($limit !== null) {{\n\
        $sql = $sql . ' LIMIT ' . (int) $limit\n\
    }}\n\
    if ($offset !== null) {{\n\
        $sql = $sql . ' OFFSET ' . (int) $offset\n\
    }}\n\
    $rows = db_rows(db_query($handle, $sql, $params))\n\
    if (!result_is_ok($rows)) {{\n\
        return $rows\n\
    }}\n\
    return apply_includes_to_rows($handle, $meta, $model, $rows->value, $includes)\n\
}}\n\n\
export function selectOne($handle, $meta, $model, $where = null, $includes = null) {{\n\
    $rows = selectMany($handle, $meta, $model, $where, null, 1, null, $includes)\n\
    if (!result_is_ok($rows)) {{\n\
        return $rows\n\
    }}\n\
    if (count($rows->value) === 0) {{\n\
        return result_err('no rows')\n\
    }}\n\
    return result_ok($rows->value[0])\n\
}}\n\n\
export function insertOne($handle, $model, $row, $returning = false) {{\n\
    $table = model_table($model)\n\
    if ($table === null) {{\n\
        return result_err('unknown model')\n\
    }}\n\
    if (!is_array($row) && !is_object($row)) {{\n\
        return result_err('insert row must be non-empty array|object')\n\
    }}\n\
    $cols = []\n\
    $values = []\n\
    $holders = []\n\
    $quoted = []\n\
    $idx = 1\n\
    foreach ($row as $col => $value) {{\n\
        $cols[] = $col\n\
        $quoted[] = quote_ident($col)\n\
        $holders[] = '$' . $idx\n\
        $values[] = $value\n\
        $idx += 1\n\
    }}\n\
    if (count($cols) === 0) {{\n\
        return result_err('insert row must be non-empty array|object')\n\
    }}\n\
    $sql = 'INSERT INTO ' . quote_ident($table) . ' (' . implode(', ', $quoted) . ') VALUES (' . implode(', ', $holders) . ')'\n\
    if ($returning) {{\n\
        $sql = $sql . ' RETURNING *'\n\
        return db_rows(db_query($handle, $sql, $values))\n\
    }}\n\
    return db_exec($handle, $sql, $values)\n\
}}\n\n\
export function updateWhere($handle, $model, $patch, $where = null, $returning = false) {{\n\
    $table = model_table($model)\n\
    if ($table === null) {{\n\
        return result_err('unknown model')\n\
    }}\n\
    if (!is_array($patch) && !is_object($patch)) {{\n\
        return result_err('update patch must be non-empty array|object')\n\
    }}\n\
    $params = []\n\
    $sets = []\n\
    foreach ($patch as $col => $value) {{\n\
        $params[] = $value\n\
        $sets[] = quote_ident($col) . ' = $' . count($params)\n\
    }}\n\
    if (count($sets) === 0) {{\n\
        return result_err('update patch must be non-empty array|object')\n\
    }}\n\
    $sql = 'UPDATE ' . quote_ident($table) . ' SET ' . implode(', ', $sets)\n\
    $where_sql = compile_predicate($where, $params)\n\
    if ($where_sql !== '') {{\n\
        $sql = $sql . ' WHERE ' . $where_sql\n\
    }}\n\
    if ($returning) {{\n\
        $sql = $sql . ' RETURNING *'\n\
        return db_rows(db_query($handle, $sql, $params))\n\
    }}\n\
    return db_exec($handle, $sql, $params)\n\
}}\n\n\
export function deleteWhere($handle, $model, $where = null) {{\n\
    $table = model_table($model)\n\
    if ($table === null) {{\n\
        return result_err('unknown model')\n\
    }}\n\
    $params = []\n\
    $sql = 'DELETE FROM ' . quote_ident($table)\n\
    $where_sql = compile_predicate($where, $params)\n\
    if ($where_sql !== '') {{\n\
        $sql = $sql . ' WHERE ' . $where_sql\n\
    }}\n\
    return db_exec($handle, $sql, $params)\n\
}}\n\n\
function insert_values_builder($handle, $model, $row) {{\n\
    return {{\n\
        'exec': fn() => insertOne($handle, $model, $row),\n\
        'returning': fn() => insert_returning_builder($handle, $model, $row)\n\
    }}\n\
}}\n\n\
function insert_returning_many($handle, $model, $row) {{\n\
    return insertOne($handle, $model, $row, true)\n\
}}\n\n\
function insert_returning_one($handle, $model, $row) {{\n\
    $rows = insertOne($handle, $model, $row, true)\n\
    if (!result_is_ok($rows)) {{\n\
        return $rows\n\
    }}\n\
    if (count($rows->value) === 0) {{\n\
        return result_err('no rows')\n\
    }}\n\
    return result_ok($rows->value[0])\n\
}}\n\n\
function insert_returning_builder($handle, $model, $row) {{\n\
    return {{\n\
        'many': fn() => insert_returning_many($handle, $model, $row),\n\
        'one': fn() => insert_returning_one($handle, $model, $row)\n\
    }}\n\
}}\n\n\
export function insert($handle, $model) {{\n\
    return {{\n\
        'values': fn($row) => insert_values_builder($handle, $model, $row)\n\
    }}\n\
}}\n\n\
function select_builder($handle, $meta, $model, $where, $order, $take, $skip, $includes) {{\n\
    return {{\n\
        'where': fn($expr) => select_builder($handle, $meta, $model, $expr, $order, $take, $skip, $includes),\n\
        'orderBy': fn($expr) => select_builder($handle, $meta, $model, $where, $expr, $take, $skip, $includes),\n\
        'limit': fn($value) => select_builder($handle, $meta, $model, $where, $order, $value, $skip, $includes),\n\
        'offset': fn($value) => select_builder($handle, $meta, $model, $where, $order, $take, $value, $includes),\n\
        'include': fn($fields) => select_builder($handle, $meta, $model, $where, $order, $take, $skip, $fields),\n\
        'many': fn() => selectMany($handle, $meta, $model, $where, $order, $take, $skip, $includes),\n\
        'one': fn() => selectOne($handle, $meta, $model, $where, $includes)\n\
    }}\n\
}}\n\n\
export function select($handle, $meta) {{\n\
    return {{\n\
        'from': fn($model) => select_builder($handle, $meta, $model, null, null, null, null, null)\n\
    }}\n\
}}\n\n\
function update_set_builder($handle, $model, $patch, $where, $returning) {{\n\
    return {{\n\
        'where': fn($expr) => update_set_builder($handle, $model, $patch, $expr, $returning),\n\
        'returning': fn() => update_set_builder($handle, $model, $patch, $where, true),\n\
        'exec': fn() => updateWhere($handle, $model, $patch, $where, false),\n\
        'many': fn() => updateWhere($handle, $model, $patch, $where, $returning),\n\
        'one': fn() => update_returning_one($handle, $model, $patch, $where)\n\
    }}\n\
}}\n\n\
function update_returning_one($handle, $model, $patch, $where) {{\n\
    $rows = updateWhere($handle, $model, $patch, $where, true)\n\
    if (!result_is_ok($rows)) {{\n\
        return $rows\n\
    }}\n\
    if (count($rows->value) === 0) {{\n\
        return result_err('no rows')\n\
    }}\n\
    return result_ok($rows->value[0])\n\
}}\n\n\
export function update($handle, $model) {{\n\
    return {{\n\
        'set': fn($patch) => update_set_builder($handle, $model, $patch, null, false)\n\
    }}\n\
}}\n\n\
function delete_builder($handle, $model, $where) {{\n\
    return {{\n\
        'where': fn($expr) => delete_builder($handle, $model, $expr),\n\
        'exec': fn() => deleteWhere($handle, $model, $where)\n\
    }}\n\
}}\n\n\
export function deleteQuery($handle, $model) {{\n\
    return delete_builder($handle, $model, null)\n\
}}\n\n\
function model_meta($meta, $model) {{\n\
    if (!is_array($meta) || !array_key_exists('models', $meta)) {{\n\
        return null\n\
    }}\n\
    $name = model_name($model)\n\
    if ($name === null || !array_key_exists($name, $meta['models'])) {{\n\
        return null\n\
    }}\n\
    return $meta['models'][$name]\n\
}}\n\n\
function relation_meta($meta, $model, $field) {{\n\
    $m = model_meta($meta, $model)\n\
    if ($m === null || !is_array($m) || !array_key_exists('relations', $m) || !is_array($m['relations'])) {{\n\
        return null\n\
    }}\n\
    foreach ($m['relations'] as $rel) {{\n\
        if (is_array($rel) && array_key_exists('field', $rel) && $rel['field'] === $field) {{\n\
            return $rel\n\
        }}\n\
    }}\n\
    return null\n\
}}\n\n\
export function loadRelation($handle, $meta, $model, $row, $field) {{\n\
    if (!is_array($row)) {{\n\
        return result_err('loadRelation expects row array')\n\
    }}\n\
    $rel = relation_meta($meta, $model, $field)\n\
    if ($rel === null) {{\n\
        return result_err('unknown relation')\n\
    }}\n\
    if (!array_key_exists('kind', $rel) || !array_key_exists('model', $rel) || !array_key_exists('foreignKey', $rel)) {{\n\
        return result_err('invalid relation metadata')\n\
    }}\n\
    $kind = $rel['kind']\n\
    $target = $rel['model']\n\
    $fk = $rel['foreignKey']\n\
    if ($kind === 'hasMany') {{\n\
        if (!array_key_exists('id', $row)) {{\n\
            return result_err('source row missing id')\n\
        }}\n\
        return selectMany($handle, $meta, $target, eq($fk, $row['id']), null, null, null, null)\n\
    }}\n\
    if ($kind === 'belongsTo' || $kind === 'hasOne') {{\n\
        if (!array_key_exists($fk, $row)) {{\n\
            return result_err('source row missing foreign key')\n\
        }}\n\
        return selectOne($handle, $meta, $target, eq('id', $row[$fk]), null)\n\
    }}\n\
    return result_err('unsupported relation kind')\n\
}}\n\n\
export function transaction($handle, $fn) {{\n\
    $started = db_begin($handle)\n\
    if (!result_is_ok($started)) {{\n\
        return $started\n\
    }}\n\
    $result = $fn($handle)\n\
    if (is_object($result) && isset($result->ok) && !$result->ok) {{\n\
        db_rollback($handle)\n\
        return $result\n\
    }}\n\
    $committed = db_commit($handle)\n\
    if (!result_is_ok($committed)) {{\n\
        db_rollback($handle)\n\
        return $committed\n\
    }}\n\
    return result_ok($result)\n\
}}\n\n\
export function createClient($meta, $handle = null) {{\n\
    return {{\n\
        meta: $meta,\n\
        handle: $handle,\n\
        models: {{\n{}        }},\n\
        withHandle: fn($nextHandle) => createClient($meta, $nextHandle),\n\
        connect: fn($driver, $config) => connect($driver, $config),\n\
        close: fn() => close($handle),\n\
        select: fn() => select($handle, $meta),\n\
        selectMany: fn($model, $where = null, $order = null, $limit = null, $offset = null, $includes = null) => selectMany($handle, $meta, $model, $where, $order, $limit, $offset, $includes),\n\
        selectOne: fn($model, $where = null, $includes = null) => selectOne($handle, $meta, $model, $where, $includes),\n\
        insert: fn($model) => insert($handle, $model),\n\
        insertOne: fn($model, $row, $returning = false) => insertOne($handle, $model, $row, $returning),\n\
        update: fn($model) => update($handle, $model),\n\
        updateWhere: fn($model, $where, $values, $returning = false) => updateWhere($handle, $model, $where, $values, $returning),\n\
        'delete': fn($model) => deleteQuery($handle, $model),\n\
        deleteWhere: fn($model, $where, $returning = false) => deleteWhere($handle, $model, $where, $returning),\n\
        loadRelation: fn($model, $row, $field) => loadRelation($handle, $meta, $model, $row, $field),\n\
        transaction: fn($fn) => transaction($handle, $fn),\n\
        eq: fn($column, $value) => eq($column, $value),\n\
        ilike: fn($column, $value) => ilike($column, $value),\n\
        isNull: fn($column) => isNull($column),\n\
        andWhere: fn(...$parts) => andWhere(...$parts),\n\
        orWhere: fn(...$parts) => orWhere(...$parts),\n\
        asc: fn($column) => asc($column),\n\
        desc: fn($column) => desc($column),\n\
        limit: fn($value) => limit($value),\n\
        offset: fn($value) => offset($value)\n\
    }}\n\
}}\n",
        GENERATED_HEADER, model_map
    );
    annotate_untyped_params(&raw)
}

pub(super) fn annotate_untyped_params(source: &str) -> String {
    let bytes = source.as_bytes();
    let mut out = String::with_capacity(source.len() + 256);
    let mut i = 0usize;
    while i < bytes.len() {
        let rest = &source[i..];
        let is_function = rest.starts_with("function ");
        let is_fn = (rest.starts_with("fn(") || rest.starts_with("fn ("))
            && (i == 0 || !is_ident_char(bytes[i - 1] as char));
        if is_function || is_fn {
            let open_idx = if is_function {
                match source[i..].find('(') {
                    Some(rel) => i + rel,
                    None => {
                        out.push(bytes[i] as char);
                        i += 1;
                        continue;
                    }
                }
            } else {
                let mut j = i + 2;
                while j < bytes.len() && source.as_bytes()[j].is_ascii_whitespace() {
                    j += 1;
                }
                if j >= bytes.len() || source.as_bytes()[j] != b'(' {
                    out.push(bytes[i] as char);
                    i += 1;
                    continue;
                }
                j
            };

            let close_idx = match matching_paren(source, open_idx) {
                Some(idx) => idx,
                None => {
                    out.push(bytes[i] as char);
                    i += 1;
                    continue;
                }
            };

            out.push_str(&source[i..=open_idx]);
            out.push_str(&annotate_param_list(&source[open_idx + 1..close_idx]));
            out.push(')');
            i = close_idx + 1;
            continue;
        }
        out.push(bytes[i] as char);
        i += 1;
    }
    out
}

fn matching_paren(source: &str, open_idx: usize) -> Option<usize> {
    let bytes = source.as_bytes();
    let mut depth = 0i32;
    let mut i = open_idx;
    while i < bytes.len() {
        match bytes[i] {
            b'(' => depth += 1,
            b')' => {
                depth -= 1;
                if depth == 0 {
                    return Some(i);
                }
            }
            _ => {}
        }
        i += 1;
    }
    None
}

fn annotate_param_list(params: &str) -> String {
    if params.trim().is_empty() {
        return String::new();
    }
    let mut parts = Vec::new();
    let mut start = 0usize;
    let mut depth_paren = 0i32;
    let mut depth_brace = 0i32;
    let mut depth_bracket = 0i32;
    let mut depth_angle = 0i32;
    let mut in_single = false;
    let mut in_double = false;
    let bytes = params.as_bytes();
    let mut i = 0usize;
    while i < bytes.len() {
        let b = bytes[i];
        if in_single {
            if b == b'\'' && (i == 0 || bytes[i - 1] != b'\\') {
                in_single = false;
            }
            i += 1;
            continue;
        }
        if in_double {
            if b == b'"' && (i == 0 || bytes[i - 1] != b'\\') {
                in_double = false;
            }
            i += 1;
            continue;
        }
        match b {
            b'\'' => in_single = true,
            b'"' => in_double = true,
            b'(' => depth_paren += 1,
            b')' => depth_paren -= 1,
            b'{' => depth_brace += 1,
            b'}' => depth_brace -= 1,
            b'[' => depth_bracket += 1,
            b']' => depth_bracket -= 1,
            b'<' => depth_angle += 1,
            b'>' => depth_angle -= 1,
            b',' if depth_paren == 0
                && depth_brace == 0
                && depth_bracket == 0
                && depth_angle == 0 =>
            {
                parts.push(annotate_single_param(&params[start..i]));
                start = i + 1;
            }
            _ => {}
        }
        i += 1;
    }
    parts.push(annotate_single_param(&params[start..]));
    parts.join(",")
}

fn annotate_single_param(param: &str) -> String {
    let bytes = param.as_bytes();
    let mut dollar_idx = None;
    for (i, b) in bytes.iter().enumerate() {
        if *b == b'$' {
            dollar_idx = Some(i);
            break;
        }
    }
    let Some(start) = dollar_idx else {
        return param.to_string();
    };
    let mut end = start + 1;
    while end < bytes.len() {
        let c = bytes[end] as char;
        if c.is_ascii_alphanumeric() || c == '_' {
            end += 1;
        } else {
            break;
        }
    }
    let mut after = end;
    while after < bytes.len() && bytes[after].is_ascii_whitespace() {
        after += 1;
    }
    if after < bytes.len() && bytes[after] == b':' {
        return param.to_string();
    }
    let mut out = String::with_capacity(param.len() + 8);
    out.push_str(&param[..end]);
    out.push_str(": mixed");
    out.push_str(&param[end..]);
    out
}

fn is_ident_char(ch: char) -> bool {
    ch.is_ascii_alphanumeric() || ch == '_' || ch == '$'
}

fn render_meta_phpx(models: &[ModelDef]) -> String {
    let mut body = String::new();
    body.push_str(GENERATED_HEADER);
    body.push_str("export function meta() {\n    return {\n    models: {\n");
    for model in models {
        let table = to_table_name(&model.name);
        let relations = model
            .fields
            .iter()
            .filter_map(|field| {
                field.relation_spec().map(|rel| {
                    format!(
                        "{{ field: '{}', kind: '{}', model: '{}', foreignKey: '{}' }}",
                        field.name, rel.kind, rel._model, rel.foreign_key
                    )
                })
            })
            .collect::<Vec<_>>()
            .join(", ");
        body.push_str(&format!("        {}: {{\n", model.name));
        body.push_str(&format!("            name: '{}',\n", model.name));
        body.push_str(&format!("            table: '{}',\n", table));
        body.push_str("            fields: {\n");
        for field in &model.fields {
            body.push_str(&format!(
                "                {}: {{ type: '{}', db_name: '{}', annotations: [{}] }},\n",
                field.name,
                field.ty,
                field.mapped_name(),
                field
                    .annotations
                    .iter()
                    .map(|ann| {
                        if ann.args.is_empty() {
                            format!("{{ name: '{}' }}", ann.name)
                        } else {
                            format!(
                                "{{ name: '{}', args: [{}] }}",
                                ann.name,
                                ann.args
                                    .iter()
                                    .map(|arg| format!("'{}'", arg.replace('\'', "\\'")))
                                    .collect::<Vec<_>>()
                                    .join(", ")
                            )
                        }
                    })
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
        body.push_str("            },\n");
        body.push_str(&format!("            relations: [{}]\n", relations));
        body.push_str("        },\n");
    }
    body.push_str("    }\n    }\n}\n");
    body
}

fn render_state_json(source: &Path, models: &[ModelDef]) -> String {
    let generated_at = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let payload = json!({
        "version": 1,
        "source": source.display().to_string(),
        "generated_at_unix": generated_at,
        "model_count": models.len(),
        "models": models.iter().map(|m| m.name.clone()).collect::<Vec<_>>(),
    });
    serde_json::to_string_pretty(&payload).unwrap_or_else(|_| "{}".to_string())
}

pub(super) fn render_generated_schema_json(models: &[ModelDef]) -> String {
    let payload = json!({
        "version": 1,
        "models": models
            .iter()
            .map(|model| {
                json!({
                    "name": model.name,
                    "table": to_table_name(&model.name),
                    "relations": model.fields
                        .iter()
                        .filter_map(|field| {
                            field.relation_spec().map(|relation| {
                                json!({
                                    "field": field.name,
                                    "kind": relation.kind,
                                    "model": relation._model,
                                    "foreignKey": relation.foreign_key,
                                })
                            })
                        })
                        .collect::<Vec<_>>(),
                    "fields": model.fields
                        .iter()
                        .map(|field| {
                            let (sql_type, nullable) = map_sql_type(&field.ty);
                            json!({
                                "name": field.name,
                                "db_name": field.mapped_name(),
                                "type": field.ty,
                                "sql_type": sql_type,
                                "nullable": nullable,
                                "annotations": field.annotations
                                    .iter()
                                    .map(|ann| json!({
                                        "name": ann.name,
                                        "args": ann.args,
                                    }))
                                    .collect::<Vec<_>>(),
                            })
                        })
                        .collect::<Vec<_>>(),
                })
            })
            .collect::<Vec<_>>(),
    });
    serde_json::to_string_pretty(&payload).unwrap_or_else(|_| "{}".to_string())
}

pub(super) fn unquote(value: &str) -> String {
    let trimmed = value.trim();
    if trimmed.len() >= 2 {
        let bytes = trimmed.as_bytes();
        if (bytes[0] == b'"' && bytes[trimmed.len() - 1] == b'"')
            || (bytes[0] == b'\'' && bytes[trimmed.len() - 1] == b'\'')
        {
            return trimmed[1..trimmed.len() - 1].to_string();
        }
    }
    trimmed.to_string()
}

pub(super) fn to_table_name(model_name: &str) -> String {
    let mut out = String::new();
    for (idx, ch) in model_name.chars().enumerate() {
        if ch.is_uppercase() {
            if idx > 0 {
                out.push('_');
            }
            for lower in ch.to_lowercase() {
                out.push(lower);
            }
        } else {
            out.push(ch);
        }
    }
    if out.ends_with('s') {
        out
    } else {
        format!("{}s", out)
    }
}

pub(super) fn map_sql_type(ty: &str) -> (&'static str, bool) {
    let trimmed = ty.trim();
    let lowered = trimmed.to_ascii_lowercase();
    if lowered == "array" || lowered.starts_with("array<") {
        return ("JSONB", false);
    }
    if let Some(inner) = trimmed
        .strip_prefix("Option<")
        .and_then(|s| s.strip_suffix('>'))
    {
        let (mapped, _) = map_sql_type(inner);
        return (mapped, true);
    }
    match trimmed {
        "int" | "i64" | "u64" | "i32" | "u32" => ("BIGINT", false),
        "float" | "double" | "f64" | "f32" => ("DOUBLE PRECISION", false),
        "bool" | "boolean" => ("BOOLEAN", false),
        "string" | "String" => ("TEXT", false),
        _ => ("TEXT", false),
    }
}
