[package]
name = "deka-ui-macros"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[lib]
proc-macro = true

[features]
hot-reload = ["dep:deka-ui-hot-reload"]

[dependencies]
deka-ui-hot-reload = { path = "../deka_ui_hot_reload", optional = true }
proc-macro2 = { version = "1", features = ["span-locations"] }
quote = "1"
syn = { version = "3", features = ["full"] }
rstml = "=0.13.1"
deka_native_ir = { path = "../deka_native_ir" }

[dev-dependencies]
bumpalo = "3"
deka_syntax = { path = "../deka_syntax" }
serde_json = "1"
