use bundler::{BuildOptions, VirtualSource, bundle_virtual_entry, optimize_emitted_module};
use core::{CommandSpec, Context, ParamSpec, Registry};
use deka_compile::module_graph::{self, GraphCompileOptions};
use std::collections::{BTreeSet, HashMap};

use crate::compile_helper::compile_js_or_report;
use std::fs;
#[cfg(unix)]
use std::os::unix::ffi::OsStrExt;
#[cfg(unix)]
use std::os::unix::io::{AsRawFd, FromRawFd};
use std::path::{Path, PathBuf};
use std::sync::Arc;

const GENERATED_MARKER: &str = "// Generated by deka transpile. Do not edit manually.\n";

const COMMAND: CommandSpec = CommandSpec {
    name: "transpile",
    category: "project",
    summary: "emit V8-target JavaScript from a .ds file or directory",
    aliases: &[],
    subcommands: &[],
    handler: cmd,
};

pub fn register(registry: &mut Registry) {
    registry.add_command(COMMAND);
    registry.add_flag(core::FlagSpec {
        name: "--preserve",
        aliases: &[],
        description: "preserve a directory's module tree (default for directories)",
    });
    registry.add_flag(core::FlagSpec {
        name: "--bundle",
        aliases: &[],
        description: "emit one resolved JavaScript module graph",
    });
    registry.add_flag(core::FlagSpec {
        name: "--treeshake",
        aliases: &[],
        description: "apply the existing JavaScript optimization path to emitted modules",
    });
    registry.add_flag(core::FlagSpec {
        name: "--client",
        aliases: &[],
        description: "treat the entry as a client bundle (ui/server is a build failure)",
    });
    registry.add_param(ParamSpec {
        name: "--out",
        description: "output .js file (file/bundle) or output directory (preserve)",
    });
}

pub fn cmd(context: &Context) {
    if context.args.flags.get("--help").copied().unwrap_or(false)
        || context.args.flags.get("-H").copied().unwrap_or(false)
        || context.args.flags.get("help").copied().unwrap_or(false)
    {
        stdio::raw(usage());
        return;
    }
    if let Err(err) = run(context) {
        stdio::error("transpile", &err);
        std::process::exit(1);
    }
}

fn run(context: &Context) -> Result<(), String> {
    let input = context
        .args
        .positionals
        .first()
        .ok_or_else(|| usage().to_string())?;
    if context.args.positionals.len() != 1 {
        return Err(usage().to_string());
    }
    let input = PathBuf::from(input);
    let mode = TranspileMode::from_context(context, &input)?;
    let output = context.args.params.get("--out").map(PathBuf::from);
    let treeshake = context
        .args
        .flags
        .get("--treeshake")
        .copied()
        .unwrap_or(false);
    let client = context
        .args
        .flags
        .get("--client")
        .copied()
        .unwrap_or(false);

    match (input.is_file(), input.is_dir()) {
        (true, _) => transpile_file(&input, output.as_deref(), mode, treeshake, client),
        (_, true) => transpile_directory(&input, output.as_deref(), mode, treeshake, client),
        _ => Err(format!("input path does not exist: {}", input.display())),
    }
}

fn usage() -> &'static str {
    "usage: deka transpile <file-or-directory> [--preserve|--bundle] [--treeshake] [--client] [--out <path>]\n\nModes:\n  file: writes adjacent <name>.js by default; --out selects the output file\n  directory: --preserve is the default and mirrors .ds paths as .js paths\n  directory --bundle: requires --out <file.js> and emits one resolved graph\n  --treeshake: applies the existing JavaScript optimization path in either mode\n  --client: fail the build if the graph can reach ui/server\n\nSecurity:\n  Output ancestors must be non-symlinked, private directories owned by this user\n  (or a non-writable root-owned system ancestor); shared paths are rejected.\n\nExamples:\n  deka transpile app/main.ds\n  deka transpile app --preserve --out generated\n  deka transpile app --bundle --out dist/app.js --treeshake\n  deka transpile island.dsx --bundle --client --out dist/island.js"
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum TranspileMode {
    Preserve,
    Bundle,
}

impl TranspileMode {
    fn from_context(context: &Context, input: &Path) -> Result<Self, String> {
        let preserve = context
            .args
            .flags
            .get("--preserve")
            .copied()
            .unwrap_or(false);
        let bundle = context.args.flags.get("--bundle").copied().unwrap_or(false);
        if preserve && bundle {
            return Err("--preserve and --bundle cannot be used together".to_string());
        }
        if bundle {
            Ok(Self::Bundle)
        } else if input.is_dir() || preserve {
            Ok(Self::Preserve)
        } else {
            Ok(Self::Preserve)
        }
    }
}

fn transpile_file(
    input: &Path,
    out: Option<&Path>,
    mode: TranspileMode,
    treeshake: bool,
    client: bool,
) -> Result<(), String> {
    require_ds(input)?;
    let output = out
        .map(PathBuf::from)
        .unwrap_or_else(|| input.with_extension("js"));
    if output == input {
        return Err("output path must differ from the .ds input path".to_string());
    }
    // Validate the source before checking output-directory security so that
    // syntax/type errors are surfaced immediately (dekaruntime/deka#117).
    let js = if mode == TranspileMode::Bundle {
        build_bundle(input, treeshake, client)?
    } else {
        build_module(input, &output, treeshake, client)?
    };
    let mappings = vec![(input.to_path_buf(), output.clone())];
    let root = SecureOutputRoot::open_or_create(output_root_parent(&output))?;
    let mut destinations = preflight_outputs(&root, &mappings)?;
    commit_outputs(
        &root,
        vec![OutputPlan {
            destination: destinations.remove(0),
            js,
        }],
    )?;
    stdio::success(&format!(
        "transpiled {} -> {}",
        input.display(),
        output.display()
    ));
    Ok(())
}

fn transpile_directory(
    input: &Path,
    out: Option<&Path>,
    mode: TranspileMode,
    treeshake: bool,
    client: bool,
) -> Result<(), String> {
    let sources = collect_ds_sources(input)?;
    if sources.is_empty() {
        return Err(format!("no .ds files found under {}", input.display()));
    }
    match mode {
        TranspileMode::Bundle => {
            let output = out.ok_or_else(|| {
                "directory --bundle requires --out <file.js> so the bundle target is unambiguous"
                    .to_string()
            })?;
            if output.is_dir() || output.extension().and_then(|ext| ext.to_str()) != Some("js") {
                return Err("directory --bundle --out must name a .js file".to_string());
            }
            let entry = directory_entry(input, &sources)?;
            // Validate the entry before checking output-directory security so
            // that syntax/type errors surface first (dekaruntime/deka#117).
            let js = build_bundle(&entry, treeshake, client)?;
            let root = SecureOutputRoot::open_or_create(output_root_parent(output))?;
            let mut destinations =
                preflight_outputs(&root, &[(entry.clone(), output.to_path_buf())])?;
            commit_outputs(
                &root,
                vec![OutputPlan {
                    destination: destinations.remove(0),
                    js,
                }],
            )?;
            stdio::success(&format!(
                "transpiled {} -> {}",
                input.display(),
                output.display()
            ));
        }
        TranspileMode::Preserve => {
            let output_root = out
                .map(PathBuf::from)
                .unwrap_or_else(|| input.to_path_buf());
            if output_root.extension().is_some() {
                return Err("directory --preserve --out must name a directory".to_string());
            }
            let mappings = sources
                .iter()
                .map(|source| {
                    source
                        .strip_prefix(input)
                        .map(|rel| (source.clone(), output_root.join(rel).with_extension("js")))
                        .map_err(|_| "failed to preserve source tree".to_string())
                })
                .collect::<Result<Vec<_>, _>>()?;
            // Validate every source before checking output-directory security so
            // that syntax/type errors surface first (dekaruntime/deka#117).
            for source in &sources {
                if source_has_imports(source)? {
                    // Imports require the module graph; build_module will
                    // compile through that path and surface any errors.
                    continue;
                }
                compile_source(source)?;
            }
            let root = SecureOutputRoot::open_or_create(&output_root)?;
            let destinations = preflight_outputs(&root, &mappings)?;
            let plans = mappings
                .iter()
                .zip(destinations)
                .map(|((source, output), destination)| {
                    build_module(source, output, treeshake, client)
                        .map(|js| OutputPlan { destination, js })
                })
                .collect::<Result<Vec<_>, _>>()?;
            commit_outputs(&root, plans)?;
            stdio::success(&format!(
                "transpiled {} -> {}",
                input.display(),
                output_root.display()
            ));
        }
    }
    Ok(())
}

fn directory_entry(root: &Path, sources: &[PathBuf]) -> Result<PathBuf, String> {
    for name in ["main.ds", "index.ds", "app.ds"] {
        let candidate = root.join(name);
        if candidate.is_file() {
            return Ok(candidate);
        }
    }
    if sources.len() == 1 {
        return Ok(sources[0].clone());
    }
    Err(format!(
        "directory --bundle needs an entry file (main.ds, index.ds, or app.ds) under {}",
        root.display()
    ))
}

fn output_root_parent(output: &Path) -> &Path {
    output
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .unwrap_or(Path::new("."))
}

fn build_module(
    input: &Path,
    output: &Path,
    treeshake: bool,
    client: bool,
) -> Result<String, String> {
    let mut js = if source_has_imports(input)? {
        compile_source_via_module_graph(input, client)?
    } else {
        compile_source(input)?
    };
    js = rewrite_relative_ds_imports(js);
    if treeshake {
        js = optimize_emitted_module(&js, output)?;
    }
    Ok(js)
}

fn source_has_imports(input: &Path) -> Result<bool, String> {
    let source = fs::read_to_string(input)
        .map_err(|err| format!("failed to read {}: {err}", input.display()))?;
    let meta = deka_compile::parse_source_module_meta(&source);
    Ok(!meta.imports.is_empty())
}

fn compile_source_via_module_graph(input: &Path, client: bool) -> Result<String, String> {
    let project_root = input
        .parent()
        .unwrap_or(Path::new("."))
        .to_path_buf();
    let loader = module_graph::FsModuleLoader::new(project_root);
    let graph = module_graph::compile_module_graph_with_options(
        input,
        &loader,
        GraphCompileOptions { client },
    )
        .map_err(|diagnostics| {
            diagnostics
                .iter()
                .map(|d| format!("{}:{}: {}", d.line, d.column, d.message))
                .collect::<Vec<_>>()
                .join("\n")
        })?;
    graph
        .modules
        .get(&graph.entry)
        .cloned()
        .ok_or_else(|| "module graph did not emit entry module".to_string())
}

fn build_bundle(
    input: &Path,
    treeshake: bool,
    client: bool,
) -> Result<String, String> {
    let entry = fs::canonicalize(input)
        .map_err(|err| format!("failed to resolve {}: {err}", input.display()))?;
    let project_root = entry.parent().unwrap_or(Path::new(".")).to_path_buf();
    let loader = module_graph::FsModuleLoader::new(project_root.clone());
    let graph = module_graph::compile_module_graph_with_options(
        &entry,
        &loader,
        GraphCompileOptions { client },
    )
    .map_err(|diagnostics| {
        diagnostics
            .iter()
            .map(|d| format!("{}:{}: {}", d.line, d.column, d.message))
            .collect::<Vec<_>>()
            .join("\n")
    })?;
    let provider = Arc::new(GraphSourceProvider {
        modules: graph.modules,
    });
    bundle_virtual_entry(
        &entry,
        BuildOptions {
            project_root,
            minify: treeshake,
            iife: false,
            client,
        },
        provider,
    )
}

fn compile_source(input: &Path) -> Result<String, String> {
    require_ds(input)?;
    let source = fs::read_to_string(input)
        .map_err(|err| format!("failed to read {}: {err}", input.display()))?;
    let input_name = input
        .to_str()
        .ok_or_else(|| format!("input path is not valid UTF-8: {}", input.display()))?;

    compile_js_or_report(&source, input_name)
}

struct GraphSourceProvider {
    modules: HashMap<PathBuf, String>,
}

impl VirtualSource for GraphSourceProvider {
    fn load_virtual(&self, path: &Path) -> Result<Option<String>, String> {
        let canon = fs::canonicalize(path).unwrap_or_else(|_| path.to_path_buf());
        if let Some(js) = self.modules.get(&canon).or_else(|| self.modules.get(path)) {
            return Ok(Some(js.clone()));
        }
        Ok(None)
    }
}

fn rewrite_relative_ds_imports(mut js: String) -> String {
    // The emitter deliberately preserves source module specifiers. The CLI's
    // output layout changes only relative .ds targets to their emitted .js peers.
    for quote in ['\'', '"'] {
        let needle = format!("from {quote}");
        let mut cursor = 0;
        while let Some(found) = js[cursor..].find(&needle) {
            let start = cursor + found + needle.len();
            let Some(end) = js[start..].find(quote) else {
                break;
            };
            let end = start + end;
            let specifier = &js[start..end];
            if (specifier.starts_with("./") || specifier.starts_with("../"))
                && (specifier.ends_with(".ds") || specifier.ends_with(".dsx"))
            {
                let ext_len = if specifier.ends_with(".dsx") { 4 } else { 3 };
                js.replace_range(end - ext_len..end, ".js");
                cursor = end - 1;
            } else {
                cursor = end + 1;
            }
        }
    }
    js
}

fn preflight_outputs(
    root: &SecureOutputRoot,
    mappings: &[(PathBuf, PathBuf)],
) -> Result<Vec<SecureDestination>, String> {
    let source_set = mappings
        .iter()
        .map(|(source, _)| source)
        .collect::<BTreeSet<_>>();
    let mut seen = BTreeSet::new();
    let mut destinations = Vec::with_capacity(mappings.len());
    for (_, output) in mappings {
        if source_set.contains(output) || !seen.insert(output) {
            return Err(format!("output collision at {}", output.display()));
        }
        destinations.push(root.prepare_destination(output)?);
    }
    Ok(destinations)
}

struct OutputPlan {
    destination: SecureDestination,
    js: String,
}

struct StagedOutput {
    destination: SecureDestination,
    staged: std::ffi::CString,
}

struct CommittedOutput {
    destination: SecureDestination,
    backup: Option<std::ffi::CString>,
}

fn commit_outputs(root: &SecureOutputRoot, plans: Vec<OutputPlan>) -> Result<(), String> {
    let mut staged = Vec::with_capacity(plans.len());
    for (index, plan) in plans.iter().enumerate() {
        run_test_phase_hook(TestPhase::Stage, index, &root.display);
        if let Err(err) = root
            .revalidate()
            .and_then(|_| plan.destination.revalidate(root))
        {
            cleanup_staged(&staged);
            return Err(err);
        }
        let temporary = match plan.destination.temporary_name(index, "new") {
            Ok(temporary) => temporary,
            Err(err) => {
                cleanup_staged(&staged);
                return Err(err);
            }
        };
        let contents = format!("{GENERATED_MARKER}{}", plan.js);
        if let Err(err) = plan.destination.stage(&temporary, contents.as_bytes()) {
            cleanup_staged(&staged);
            return Err(format!(
                "failed to stage {}: {err}",
                plan.destination.output.display()
            ));
        }
        staged.push(StagedOutput {
            destination: plan.destination.try_clone()?,
            staged: temporary,
        });
    }

    run_test_commit_hook();
    let mut committed = Vec::with_capacity(staged.len());
    for (index, staged_output) in staged.iter().enumerate() {
        run_test_phase_hook(TestPhase::Commit, index, &root.display);
        // Test-only rollback hooks are installed at this revalidation seam so a
        // deterministic topology change exercises cleanup after prior commits.
        run_test_phase_hook(TestPhase::Rollback, index, &root.display);
        if let Err(err) = root
            .revalidate()
            .and_then(|_| staged_output.destination.revalidate(root))
        {
            rollback_outputs(&committed, &staged);
            return Err(err);
        }
        let backup = if staged_output.destination.expected_existing {
            let backup = match staged_output.destination.temporary_name(index, "backup") {
                Ok(backup) => backup,
                Err(err) => {
                    rollback_outputs(&committed, &staged);
                    return Err(err);
                }
            };
            if let Err(err) = staged_output.destination.backup(&backup) {
                rollback_outputs(&committed, &staged);
                return Err(format!(
                    "failed to stage existing {}: {err}",
                    staged_output.destination.output.display()
                ));
            }
            Some(backup)
        } else {
            if staged_output.destination.exists_no_follow()? {
                rollback_outputs(&committed, &staged);
                return Err(format!(
                    "output changed after preflight: {}",
                    staged_output.destination.output.display()
                ));
            }
            None
        };
        if let Err(err) = staged_output.destination.commit(&staged_output.staged) {
            let current = CommittedOutput {
                destination: staged_output.destination.try_clone()?,
                backup,
            };
            rollback_outputs(std::slice::from_ref(&current), &staged);
            rollback_outputs(&committed, &staged);
            return Err(format!(
                "failed to commit {}: {err}",
                staged_output.destination.output.display()
            ));
        }
        committed.push(CommittedOutput {
            destination: staged_output.destination.try_clone()?,
            backup,
        });
    }
    for committed_output in committed {
        if let Some(backup) = committed_output.backup {
            let _ = committed_output.destination.remove(&backup);
        }
    }
    Ok(())
}

fn cleanup_staged(staged: &[StagedOutput]) {
    for staged_output in staged {
        let _ = staged_output.destination.remove(&staged_output.staged);
    }
}

fn rollback_outputs(committed: &[CommittedOutput], staged: &[StagedOutput]) {
    for committed_output in committed.iter().rev() {
        let _ = committed_output
            .destination
            .remove(&committed_output.destination.leaf);
        if let Some(backup) = &committed_output.backup {
            let _ = committed_output.destination.restore(backup);
        }
    }
    cleanup_staged(staged);
}

#[cfg(unix)]
struct SecureOutputRoot {
    dir: fs::File,
    parent: Option<fs::File>,
    name: Option<std::ffi::CString>,
    identity: (u64, u64),
    display: PathBuf,
    lexical: PathBuf,
}

#[cfg(unix)]
struct SecureDestination {
    parent: fs::File,
    parent_identity: (u64, u64),
    relative_parent: PathBuf,
    leaf: std::ffi::CString,
    expected_existing: bool,
    output: PathBuf,
}

#[cfg(unix)]
impl SecureOutputRoot {
    fn open_or_create(path: &Path) -> Result<Self, String> {
        let lexical = path.to_path_buf();
        let path = trusted_root_path(path)?;
        let mut dir = if path.is_absolute() {
            open_dir_path(Path::new("/"))?
        } else {
            open_dir_path(Path::new("."))?
        };
        ensure_trusted_dir(&dir)?;
        let mut prior = None;
        let mut name = None;
        for component in path.components() {
            if matches!(
                component,
                std::path::Component::RootDir | std::path::Component::CurDir
            ) {
                continue;
            }
            let std::path::Component::Normal(part) = component else {
                return Err(format!("unsafe output root: {}", path.display()));
            };
            let part = cstring(part)?;
            let parent = dir.try_clone().map_err(|err| err.to_string())?;
            dir = open_or_create_dir(&parent, &part)?;
            prior = Some(parent);
            name = Some(part);
        }
        Ok(Self {
            identity: identity(&dir)?,
            dir,
            parent: prior,
            name,
            display: path,
            lexical,
        })
    }

    fn revalidate(&self) -> Result<(), String> {
        if let (Some(parent), Some(name)) = (&self.parent, &self.name) {
            let current = open_dir_at(parent, name)?;
            ensure_trusted_dir(&current)?;
            if identity(&current)? != self.identity {
                return Err(format!(
                    "output root changed after preflight: {}",
                    self.display.display()
                ));
            }
        }
        Ok(())
    }

    fn prepare_destination(&self, output: &Path) -> Result<SecureDestination, String> {
        let relative = output
            .strip_prefix(&self.lexical)
            .map_err(|_| format!("output escapes declared root: {}", output.display()))?;
        let leaf = relative
            .file_name()
            .ok_or_else(|| format!("invalid output path: {}", output.display()))?;
        let mut parent = self.dir.try_clone().map_err(|err| err.to_string())?;
        let parent_rel = relative.parent().unwrap_or(Path::new(""));
        for component in parent_rel.components() {
            let std::path::Component::Normal(part) = component else {
                return Err(format!("unsafe output path: {}", output.display()));
            };
            parent = open_or_create_dir(&parent, &cstring(part)?)?;
        }
        let leaf = cstring(leaf)?;
        let expected_existing = match file_kind(&parent, &leaf)? {
            None => false,
            Some(libc::S_IFREG) => generated_marker(&parent, &leaf)?,
            Some(libc::S_IFLNK) => {
                return Err(format!("symlinked output rejected: {}", output.display()));
            }
            _ => {
                return Err(format!(
                    "output collision: {} is not a regular file",
                    output.display()
                ));
            }
        };
        if file_kind(&parent, &leaf)?.is_some() && !expected_existing {
            return Err(format!(
                "output collision: {} already exists and was not generated by deka transpile",
                output.display()
            ));
        }
        Ok(SecureDestination {
            parent_identity: identity(&parent)?,
            parent,
            relative_parent: parent_rel.to_path_buf(),
            leaf,
            expected_existing,
            output: output.to_path_buf(),
        })
    }
}

#[cfg(unix)]
impl SecureDestination {
    fn try_clone(&self) -> Result<Self, String> {
        Ok(Self {
            parent: self.parent.try_clone().map_err(|err| err.to_string())?,
            parent_identity: self.parent_identity,
            relative_parent: self.relative_parent.clone(),
            leaf: self.leaf.clone(),
            expected_existing: self.expected_existing,
            output: self.output.clone(),
        })
    }
    fn revalidate(&self, root: &SecureOutputRoot) -> Result<(), String> {
        let mut current = root.dir.try_clone().map_err(|err| err.to_string())?;
        for component in self.relative_parent.components() {
            if let std::path::Component::Normal(part) = component {
                current = open_dir_at(&current, &cstring(part)?)?;
            }
        }
        if identity(&current)? != self.parent_identity {
            return Err(format!(
                "output parent changed after preflight: {}",
                self.output.display()
            ));
        }
        ensure_trusted_dir(&current)?;
        Ok(())
    }
    fn temporary_name(&self, index: usize, kind: &str) -> Result<std::ffi::CString, String> {
        let name = self.leaf.to_string_lossy();
        std::ffi::CString::new(format!(
            ".{name}.deka-transpile-{}-{index}.{kind}",
            std::process::id()
        ))
        .map_err(|_| "invalid temporary output name".to_string())
    }
    fn stage(&self, name: &std::ffi::CString, bytes: &[u8]) -> Result<(), String> {
        let fd = unsafe {
            libc::openat(
                self.parent.as_raw_fd(),
                name.as_ptr(),
                libc::O_WRONLY | libc::O_CREAT | libc::O_EXCL | libc::O_NOFOLLOW | libc::O_CLOEXEC,
                0o600,
            )
        };
        if fd < 0 {
            return Err(std::io::Error::last_os_error().to_string());
        }
        let mut file = unsafe { fs::File::from_raw_fd(fd) };
        std::io::Write::write_all(&mut file, bytes).map_err(|err| err.to_string())
    }
    fn exists_no_follow(&self) -> Result<bool, String> {
        Ok(file_kind(&self.parent, &self.leaf)?.is_some())
    }
    fn backup(&self, name: &std::ffi::CString) -> Result<(), String> {
        if self.exists_no_follow()? == false {
            return Err("output disappeared after preflight".to_string());
        }
        rename_at(&self.parent, &self.leaf, &self.parent, name)
    }
    fn commit(&self, staged: &std::ffi::CString) -> Result<(), String> {
        rename_at(&self.parent, staged, &self.parent, &self.leaf)
    }
    fn remove(&self, name: &std::ffi::CString) -> Result<(), String> {
        unlink_at(&self.parent, name)
    }
    fn restore(&self, backup: &std::ffi::CString) -> Result<(), String> {
        rename_at(&self.parent, backup, &self.parent, &self.leaf)
    }
}

#[cfg(unix)]
fn cstring(value: &std::ffi::OsStr) -> Result<std::ffi::CString, String> {
    std::ffi::CString::new(value.as_bytes()).map_err(|_| "path contains NUL".to_string())
}
#[cfg(unix)]
fn trusted_root_path(path: &Path) -> Result<PathBuf, String> {
    let mut missing = Vec::new();
    let mut current = path;
    loop {
        match fs::symlink_metadata(current) {
            Ok(metadata) => {
                if metadata.file_type().is_symlink() {
                    return Err(format!(
                        "symlinked output root rejected: {}",
                        current.display()
                    ));
                }
                let mut trusted = fs::canonicalize(current).map_err(|err| err.to_string())?;
                for part in missing.iter().rev() {
                    trusted.push(part);
                }
                return Ok(trusted);
            }
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {
                missing.push(
                    current
                        .file_name()
                        .ok_or_else(|| format!("invalid output root: {}", path.display()))?
                        .to_os_string(),
                );
                current = current
                    .parent()
                    .ok_or_else(|| format!("invalid output root: {}", path.display()))?;
            }
            Err(error) => return Err(error.to_string()),
        }
    }
}
#[cfg(unix)]
fn open_dir_path(path: &Path) -> Result<fs::File, String> {
    let name = cstring(path.as_os_str())?;
    let fd = unsafe {
        libc::open(
            name.as_ptr(),
            libc::O_RDONLY | libc::O_DIRECTORY | libc::O_NOFOLLOW | libc::O_CLOEXEC,
        )
    };
    if fd < 0 {
        Err(std::io::Error::last_os_error().to_string())
    } else {
        Ok(unsafe { fs::File::from_raw_fd(fd) })
    }
}
#[cfg(unix)]
fn open_dir_at(parent: &fs::File, name: &std::ffi::CString) -> Result<fs::File, String> {
    let fd = unsafe {
        libc::openat(
            parent.as_raw_fd(),
            name.as_ptr(),
            libc::O_RDONLY | libc::O_DIRECTORY | libc::O_NOFOLLOW | libc::O_CLOEXEC,
        )
    };
    if fd < 0 {
        Err(std::io::Error::last_os_error().to_string())
    } else {
        Ok(unsafe { fs::File::from_raw_fd(fd) })
    }
}
#[cfg(unix)]
fn open_or_create_dir(parent: &fs::File, name: &std::ffi::CString) -> Result<fs::File, String> {
    match open_dir_at(parent, name) {
        Ok(dir) => {
            ensure_trusted_dir(&dir)?;
            Ok(dir)
        }
        Err(_) => {
            let rc = unsafe { libc::mkdirat(parent.as_raw_fd(), name.as_ptr(), 0o700) };
            if rc != 0 && std::io::Error::last_os_error().raw_os_error() != Some(libc::EEXIST) {
                return Err(std::io::Error::last_os_error().to_string());
            }
            let dir = open_dir_at(parent, name)?;
            ensure_trusted_dir(&dir)?;
            Ok(dir)
        }
    }
}
#[cfg(unix)]
fn ensure_trusted_dir(dir: &fs::File) -> Result<(), String> {
    let stat = dir_stat(dir)?;
    let effective_uid = unsafe { libc::geteuid() };
    let writable_by_untrusted = stat.st_mode & (libc::S_IWGRP | libc::S_IWOTH) != 0;
    let trusted_owner = stat.st_uid == effective_uid || stat.st_uid == 0;
    if !trusted_owner || writable_by_untrusted {
        return Err(format!(
            "secure output topology rejected: directory must be owned by the effective user or root and not group/world writable (uid {}, mode {:o})",
            stat.st_uid,
            stat.st_mode & 0o7777
        ));
    }
    Ok(())
}
#[cfg(unix)]
fn identity(file: &fs::File) -> Result<(u64, u64), String> {
    let stat = dir_stat(file)?;
    Ok((stat.st_dev as u64, stat.st_ino as u64))
}
#[cfg(unix)]
fn dir_stat(file: &fs::File) -> Result<libc::stat, String> {
    let mut stat = unsafe { std::mem::zeroed::<libc::stat>() };
    if unsafe { libc::fstat(file.as_raw_fd(), &mut stat) } != 0 {
        Err(std::io::Error::last_os_error().to_string())
    } else {
        Ok(stat)
    }
}
#[cfg(unix)]
fn file_kind(parent: &fs::File, name: &std::ffi::CString) -> Result<Option<libc::mode_t>, String> {
    let mut stat = unsafe { std::mem::zeroed::<libc::stat>() };
    let rc = unsafe {
        libc::fstatat(
            parent.as_raw_fd(),
            name.as_ptr(),
            &mut stat,
            libc::AT_SYMLINK_NOFOLLOW,
        )
    };
    if rc == 0 {
        Ok(Some(stat.st_mode & libc::S_IFMT))
    } else if std::io::Error::last_os_error().raw_os_error() == Some(libc::ENOENT) {
        Ok(None)
    } else {
        Err(std::io::Error::last_os_error().to_string())
    }
}
#[cfg(unix)]
fn generated_marker(parent: &fs::File, name: &std::ffi::CString) -> Result<bool, String> {
    let fd = unsafe {
        libc::openat(
            parent.as_raw_fd(),
            name.as_ptr(),
            libc::O_RDONLY | libc::O_NOFOLLOW | libc::O_CLOEXEC,
        )
    };
    if fd < 0 {
        return Err(std::io::Error::last_os_error().to_string());
    }
    let mut file = unsafe { fs::File::from_raw_fd(fd) };
    let mut marker = vec![0; GENERATED_MARKER.len()];
    use std::io::Read;
    file.read_exact(&mut marker)
        .map(|_| marker == GENERATED_MARKER.as_bytes())
        .or_else(|err| {
            if err.kind() == std::io::ErrorKind::UnexpectedEof {
                Ok(false)
            } else {
                Err(err)
            }
        })
        .map_err(|err| err.to_string())
}
#[cfg(unix)]
fn rename_at(
    from_parent: &fs::File,
    from: &std::ffi::CString,
    to_parent: &fs::File,
    to: &std::ffi::CString,
) -> Result<(), String> {
    if unsafe {
        libc::renameat(
            from_parent.as_raw_fd(),
            from.as_ptr(),
            to_parent.as_raw_fd(),
            to.as_ptr(),
        )
    } != 0
    {
        Err(std::io::Error::last_os_error().to_string())
    } else {
        Ok(())
    }
}
#[cfg(unix)]
fn unlink_at(parent: &fs::File, name: &std::ffi::CString) -> Result<(), String> {
    if unsafe { libc::unlinkat(parent.as_raw_fd(), name.as_ptr(), 0) } != 0
        && std::io::Error::last_os_error().raw_os_error() != Some(libc::ENOENT)
    {
        Err(std::io::Error::last_os_error().to_string())
    } else {
        Ok(())
    }
}

#[cfg(not(unix))]
struct SecureOutputRoot;
#[cfg(not(unix))]
struct SecureDestination;
#[cfg(not(unix))]
impl SecureOutputRoot {
    fn open_or_create(_: &Path) -> Result<Self, String> {
        Err("secure transpile output is unsupported on this platform".to_string())
    }
}

#[cfg(not(test))]
fn run_test_commit_hook() {}

#[derive(Clone, Copy, PartialEq, Eq)]
enum TestPhase {
    Stage,
    Commit,
    Rollback,
}

#[cfg(not(test))]
fn run_test_phase_hook(_: TestPhase, _: usize, _: &Path) {}

#[cfg(test)]
type CommitHook = Box<dyn FnOnce() + Send>;
#[cfg(test)]
static COMMIT_HOOK: std::sync::OnceLock<std::sync::Mutex<Option<CommitHook>>> =
    std::sync::OnceLock::new();
#[cfg(test)]
static COMMIT_HOOK_TEST_GUARD: std::sync::Mutex<()> = std::sync::Mutex::new(());
#[cfg(test)]
fn run_test_commit_hook() {
    if let Some(hook) = COMMIT_HOOK
        .get_or_init(|| std::sync::Mutex::new(None))
        .lock()
        .expect("hook lock")
        .take()
    {
        hook();
    }
}

#[cfg(test)]
/// Test hook. Takes the output root because `PHASE_HOOK` is process-global:
/// without it, a hook installed by one test also fired inside every other
/// transpile test running concurrently, and performed its directory swap
/// against *their* output (deka#427).
type PhaseHook = Box<dyn Fn(TestPhase, usize, &Path) + Send + Sync>;
#[cfg(test)]
static PHASE_HOOK: std::sync::OnceLock<std::sync::Mutex<Option<PhaseHook>>> =
    std::sync::OnceLock::new();
#[cfg(test)]
static PHASE_HOOK_TEST_GUARD: std::sync::Mutex<()> = std::sync::Mutex::new(());
#[cfg(test)]
fn run_test_phase_hook(phase: TestPhase, index: usize, output_root: &Path) {
    // Recover from poisoning instead of panicking. Every transpile test calls
    // this, but only the parent-swap tests install a hook, so one panicking
    // test used to take five to seven unrelated tests down with it and bury
    // the real failure (deka#427). The guarded data is an Option<PhaseHook>
    // that a panicking test leaves as garbage at worst -- there is no
    // invariant here that poisoning protects.
    if let Some(hook) = PHASE_HOOK
        .get_or_init(|| std::sync::Mutex::new(None))
        .lock()
        .unwrap_or_else(|poisoned| poisoned.into_inner())
        .as_ref()
    {
        hook(phase, index, output_root);
    }
}

fn collect_ds_sources(root: &Path) -> Result<Vec<PathBuf>, String> {
    let mut out = Vec::new();
    collect_ds_sources_inner(root, &mut out)?;
    out.sort();
    Ok(out)
}

fn collect_ds_sources_inner(dir: &Path, out: &mut Vec<PathBuf>) -> Result<(), String> {
    let mut entries = fs::read_dir(dir)
        .map_err(|err| format!("failed to read {}: {err}", dir.display()))?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|err| format!("failed to read {}: {err}", dir.display()))?;
    entries.sort_by_key(|entry| entry.file_name());
    for entry in entries {
        let path = entry.path();
        if path.is_dir() {
            collect_ds_sources_inner(&path, out)?;
        } else if is_ds(&path) {
            out.push(path);
        }
    }
    Ok(())
}

fn require_ds(path: &Path) -> Result<(), String> {
    if is_ds(path) {
        Ok(())
    } else {
        Err(format!(
            "DekaScript uses .ds or .dsx; cannot transpile {}",
            path.display()
        ))
    }
}

fn is_ds(path: &Path) -> bool {
    matches!(
        path.extension().and_then(|ext| ext.to_str()),
        Some("ds") | Some("dsx")
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::process::Command;
    #[cfg(unix)]
    use std::sync::atomic::{AtomicBool, Ordering};
    #[cfg(unix)]
    use std::sync::Arc;

    fn write(path: &Path, source: &str) {
        fs::create_dir_all(path.parent().expect("parent")).expect("mkdir");
        fs::write(path, source).expect("write fixture");
    }

    #[test]
    fn file_output_is_adjacent_and_executes_when_node_is_available() {
        let temp = tempfile::tempdir().expect("tempdir");
        let input = temp.path().join("answer.ds");
        write(&input, "export const answer = 42;\n");
        transpile_file(&input, None, TranspileMode::Preserve, false, false)
            .expect("transpile");
        let output = input.with_extension("js");
        let emitted = fs::read_to_string(&output).expect("output");
        assert!(emitted.starts_with(GENERATED_MARKER));
        assert!(emitted.contains("answer"));
        if Command::new("node").arg("--version").output().is_ok() {
            write(&temp.path().join("package.json"), "{\"type\":\"module\"}\n");
            let check = Command::new("node")
                .args([
                    "--input-type=module",
                    "-e",
                    "import('./answer.js').then(m => { if (m.answer !== 42) process.exit(1); })",
                ])
                .current_dir(temp.path())
                .output()
                .expect("run node");
            assert!(
                check.status.success(),
                "{}",
                String::from_utf8_lossy(&check.stderr)
            );
        }
    }

    #[test]
    fn preserve_mirrors_tree_and_rewrites_relative_ds_imports() {
        let temp = tempfile::tempdir().expect("tempdir");
        let root = temp.path().join("src");
        write(
            &root.join("nested/math.ds"),
            include_str!("../../tests/fixtures/transpile/tree/nested/math.ds"),
        );
        write(
            &root.join("main.ds"),
            include_str!("../../tests/fixtures/transpile/tree/main.ds"),
        );
        let out = temp.path().join("generated");
        transpile_directory(&root, Some(&out), TranspileMode::Preserve, false, false)
            .expect("transpile");
        assert!(out.join("nested/math.js").is_file());
        assert!(
            fs::read_to_string(out.join("main.js"))
                .expect("main")
                .contains("./nested/math.js")
        );
    }

    #[test]
    fn bundle_requires_explicit_file_for_directory_and_treeshakes() {
        let temp = tempfile::tempdir().expect("tempdir");
        let root = temp.path().join("src");
        write(
            &root.join("dep.ds"),
            include_str!("../../tests/fixtures/transpile/bundle/dep.ds"),
        );
        write(
            &root.join("main.ds"),
            include_str!("../../tests/fixtures/transpile/bundle/main.ds"),
        );
        let err = transpile_directory(&root, None, TranspileMode::Bundle, true, false)
            .expect_err("needs out");
        assert!(err.contains("requires --out"));
        let out = temp.path().join("bundle.js");
        transpile_directory(&root, Some(&out), TranspileMode::Bundle, true, false)
            .expect("bundle");
        let emitted = fs::read_to_string(out).expect("bundle output");
        assert!(emitted.starts_with(GENERATED_MARKER));
        assert!(emitted.contains("answer"), "{emitted}");
        assert!(!emitted.contains("from './dep.ds'"), "{emitted}");
        assert!(!emitted.contains("unused"), "{emitted}");
    }

    #[test]
    fn bundle_drops_unused_export_without_minify() {
        let temp = tempfile::tempdir().expect("tempdir");
        let root = temp.path().join("src");
        write(
            &root.join("lib.ds"),
            "export fn keep() { return \"KEEP_ME\"; }\nexport fn drop() { return \"DROP_ME_UNIQUE\"; }\n",
        );
        write(
            &root.join("main.ds"),
            "import { keep } from \"./lib.ds\";\nexport const answer = keep();\n",
        );
        let out = temp.path().join("bundle.js");
        transpile_directory(&root, Some(&out), TranspileMode::Bundle, false, false)
            .expect("bundle");
        let emitted = fs::read_to_string(out).expect("bundle output");
        assert!(emitted.contains("KEEP_ME"), "{emitted}");
        assert!(
            !emitted.contains("DROP_ME_UNIQUE"),
            "unused export must be shaken without minify: {emitted}"
        );
    }

    #[test]
    fn client_bundle_rejects_ui_server() {
        let temp = tempfile::tempdir().expect("tempdir");
        let input = temp.path().join("island.dsx");
        write(
            &input,
            "import { renderToString } from \"ui/server\";\nexport const x = 1;\n",
        );
        let err = transpile_file(
            &input,
            None,
            TranspileMode::Bundle,
            false,
            true,
        )
        .expect_err("client + ui/server");
        assert!(
            err.contains("ui/server"),
            "{err}"
        );
    }

    #[test]
    fn rejects_invalid_input_flags_and_unowned_output_collision() {
        let temp = tempfile::tempdir().expect("tempdir");
        let txt = temp.path().join("bad.txt");
        write(&txt, "nope\n");
        assert!(
            transpile_file(&txt, None, TranspileMode::Preserve, false, false).is_err()
        );
        let input = temp.path().join("main.ds");
        let output = temp.path().join("main.js");
        write(&input, "export const value = 1;\n");
        write(&output, "customer file\n");
        assert!(
            transpile_file(
                &input,
                Some(&output),
                TranspileMode::Preserve,
                false,
                false,
            )
            .expect_err("collision")
            .contains("output collision")
        );
    }

    #[test]
    fn directory_collision_preflight_leaves_all_declared_outputs_untouched() {
        let temp = tempfile::tempdir().expect("tempdir");
        let root = temp.path().join("src");
        write(&root.join("main.ds"), "export const main = 1;\n");
        write(&root.join("nested/math.ds"), "export const math = 2;\n");
        let protected = root.join("nested/math.js");
        write(&protected, "customer file\n");

        let error = transpile_directory(
            &root,
            None,
            TranspileMode::Preserve,
            false,
            false,
        )
        .expect_err("preflight collision");

        assert!(error.contains("output collision"));
        assert!(
            !root.join("main.js").exists(),
            "a sibling output was written before collision validation"
        );
        assert_eq!(
            fs::read_to_string(protected).expect("protected output"),
            "customer file\n"
        );
    }

    #[cfg(unix)]
    #[test]
    fn rejects_symlinked_output_parent_without_writing_outside_root() {
        let temp = tempfile::tempdir().expect("tempdir");
        let root = temp.path().join("src");
        let output = temp.path().join("generated");
        let outside = temp.path().join("outside");
        write(&root.join("nested/math.ds"), "export const math = 2;\n");
        fs::create_dir_all(&outside).expect("outside");
        fs::create_dir_all(&output).expect("output");
        std::os::unix::fs::symlink(&outside, output.join("nested")).expect("symlink");

        assert!(transpile_directory(
            &root,
            Some(&output),
            TranspileMode::Preserve,
            false,
            false,
        )
        .is_err());
        assert!(!outside.join("math.js").exists());
    }

    #[cfg(unix)]
    fn assert_no_transaction_residue(dir: &Path, phase: &str) {
        for entry in fs::read_dir(dir).expect("transaction directory") {
            let entry = entry.expect("transaction entry");
            assert!(
                !entry
                    .file_name()
                    .to_string_lossy()
                    .contains(".deka-transpile-"),
                "{phase}: transaction residue at {}",
                entry.path().display()
            );
        }
    }

    #[cfg(unix)]
    #[allow(clippy::too_many_arguments)]
    fn parent_swap_hook(
        phase: TestPhase,
        target_phase: TestPhase,
        index: usize,
        target_index: usize,
        run_output_root: &Path,
        output: &Path,
        outside: &Path,
        moved: &Path,
        swapped: &AtomicBool,
    ) {
        if phase != target_phase || index != target_index {
            return;
        }
        // Another test's transpile run reaching this global hook. Swapping its
        // directories is what produced the AlreadyExists and IsADirectory
        // panics attributed to unrelated tests (deka#427).
        //
        // Compare resolved paths: the runtime canonicalizes the output root, so
        // on macOS it arrives as /private/var/... while the test holds
        // /var/... -- the same directory, two spellings.
        let resolve = |path: &Path| std::fs::canonicalize(path).unwrap_or_else(|_| path.to_path_buf());
        if resolve(run_output_root) != resolve(output) {
            return;
        }
        // Swap exactly once. The hook can be reached more than once for the
        // same (phase, index), and the second `rename` then failed with
        // `IsADirectory` because `moved` already existed -- a real panic, which
        // poisoned the hook mutex and cascaded (deka#427). "Deterministic
        // parent swap" means one swap.
        if swapped.load(Ordering::Acquire) {
            return;
        }
        let nested = output.join("nested");
        fs::rename(&nested, moved).expect("move trusted parent outside output root");
        std::os::unix::fs::symlink(outside, &nested).expect("replace parent with outside symlink");
        swapped.store(true, Ordering::Release);
    }

    #[cfg(unix)]
    fn deterministic_parent_swap_cannot_escape_or_leave_residue(
        phase: TestPhase,
        target_index: usize,
        preserve_existing_output: bool,
    ) {
        let temp = tempfile::tempdir().expect("tempdir");
        let root = temp.path().join("src");
        let output = temp.path().join("generated");
        let outside = temp.path().join("outside");
        let moved = outside.join("moved-nested");
        write(&root.join("first.ds"), "export const first = 1;\n");
        write(&root.join("nested/math.ds"), "export const math = 2;\n");
        fs::create_dir_all(&outside).expect("outside");
        fs::create_dir_all(output.join("nested")).expect("output parent");
        let original = format!("{GENERATED_MARKER}export const old = true;\n");
        if preserve_existing_output {
            write(&output.join("first.js"), &original);
        }

        let _guard = PHASE_HOOK_TEST_GUARD
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner());
        let swapped = Arc::new(AtomicBool::new(false));
        let hook_output = output.clone();
        let hook_outside = outside.clone();
        let hook_moved = moved.clone();
        let hook_swapped = Arc::clone(&swapped);
        *PHASE_HOOK
            .get_or_init(|| std::sync::Mutex::new(None))
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner()) =
            Some(Box::new(move |current_phase, index, run_output_root| {
            parent_swap_hook(
                current_phase,
                phase,
                index,
                target_index,
                run_output_root,
                &hook_output,
                &hook_outside,
                &hook_moved,
                &hook_swapped,
            );
        }));
        let error = transpile_directory(
            &root,
            Some(&output),
            TranspileMode::Preserve,
            false,
            false,
        )
        .expect_err("swapped output parent must be rejected");
        *PHASE_HOOK
            .get_or_init(|| std::sync::Mutex::new(None))
            .lock()
            .unwrap_or_else(|poisoned| poisoned.into_inner()) = None;

        assert!(swapped.load(Ordering::Acquire), "phase hook did not run");
        assert!(!error.is_empty(), "topology change must report an error");
        assert!(!outside.join("math.js").exists(), "external write");
        assert!(!moved.join("math.js").exists(), "escaped output");
        assert_no_transaction_residue(&outside, "outside");
        assert_no_transaction_residue(&moved, "moved parent");
        assert_no_transaction_residue(&output, "output root");
        assert_no_transaction_residue(&output.join("nested"), "external target");
        assert_no_transaction_residue(&root, "source root");
        assert_eq!(
            fs::read_to_string(output.join("first.js")).ok(),
            preserve_existing_output.then_some(original),
            "rollback must restore the pre-existing generated output"
        );

        fs::remove_file(output.join("nested")).expect("remove outside symlink");
        fs::rename(&moved, output.join("nested")).expect("restore trusted parent");
        assert!(
            fs::read_dir(output.join("nested"))
                .expect("output parent")
                .next()
                .is_none(),
            "no staged residue after restoring parent"
        );
    }

    #[cfg(unix)]
    #[test]
    fn concurrent_parent_swap_at_staging_cannot_write_or_leave_residue() {
        deterministic_parent_swap_cannot_escape_or_leave_residue(TestPhase::Stage, 0, false);
    }

    #[cfg(unix)]
    #[test]
    fn concurrent_parent_swap_at_commit_cannot_write_or_leave_residue() {
        deterministic_parent_swap_cannot_escape_or_leave_residue(TestPhase::Commit, 0, false);
    }

    #[cfg(unix)]
    #[test]
    fn concurrent_parent_swap_at_rollback_cannot_write_or_leave_residue() {
        deterministic_parent_swap_cannot_escape_or_leave_residue(TestPhase::Rollback, 1, true);
    }

    #[test]
    fn help_documents_modes_defaults_outputs_and_examples() {
        let help = usage();
        for expected in [
            "Modes:",
            "by default",
            "--out",
            "Examples:",
            "--treeshake",
            "Output ancestors must be non-symlinked",
        ] {
            assert!(help.contains(expected), "missing {expected} from {help}");
        }
    }

}
