[package]
name = "cli"
version = "0.9.2"
edition = "2024"

[features]
default = ["native"]
native = [
  "dep:compile",
  "dep:pm",
  "dep:runtime",
  "dep:introspect",
  "dep:tokio",
  "dep:postgres",
  "dep:php-rs",
  "dep:dekascript_lsp",
  "dep:modules_php",
  "dep:phpx_js",
  "dep:bundler",
  "dep:seam_ts",
  "dep:rusqlite",
]

[dependencies]
runtime = { path = "../runtime", optional = true }
runtime_core = { path = "../runtime_core" }
seam_diff = { path = "../seam_diff" }
seam_ir = { path = "../seam_ir" }
seam_ts = { path = "../seam_ts", optional = true }
compile = { path = "../compile", optional = true }
core = { path ="../core" }
stdio = { path = "../stdio" }
introspect = { path = "../introspect", optional = true }
wasm_cli = { path = "../wasm_cli" }
pm = { workspace = true, optional = true }
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1.35", features = ["rt-multi-thread", "net", "io-util"], optional = true }
postgres = { version = "0.19", optional = true }
php-rs = { path = "../php-rs", optional = true }
dekascript_lsp = { path = "../phpx_lsp", optional = true }
modules_php = { path = "../modules_php", optional = true }
phpx_js = { path = "../phpx_js", optional = true }
bumpalo = "3.12"
rusqlite = { version = "0.32", optional = true }
sha2 = "0.10"
ctrlc = "3"
deno_task_shell = "0.29.0"
glob = "0.3.1"
serde_yaml = "0.9"
bundler = { path = "../bundler", optional = true }
libc = "0.2"

[dev-dependencies]
tempfile = "3.23.0"
