[package]
name = "deka-router"
version = "0.23.5"
edition = "2024"

[[bin]]
name = "deka-router"
path = "src/main.rs"

[dependencies]
axum = { workspace = true }
bytes = { workspace = true }
deka-shard = { path = "../shard" }
redis = { workspace = true }
reqwest = { version = "0.11", features = ["stream"] }
zega-core = { path = "../zega/zega-core" }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["full"] }
