[package]
name = "seam_ts"
version = "0.1.0"
edition = "2024"

[dependencies]
seam_ir = { path = "../seam_ir" }
swc_common = { workspace = true }
swc_ecma_ast = { workspace = true }
swc_ecma_parser = { workspace = true, features = ["typescript"] }

[dev-dependencies]
serde_json = { workspace = true }
