// Generated by dsc transpile. Do not edit manually.
"use strict";
import { jsx, jsxs, Fragment } from "ui/jsx";
import { live } from "ui/reactive";
function __deka_struct(id,embeds){function f(fields){return Object.assign({__proto__:f.prototype},fields);}f.id=id;Object.defineProperty(f,'name',{value:id,configurable:true});if(embeds)Object.defineProperty(f,'__deka_embeds',{value:embeds,enumerable:false,writable:false,configurable:false});f.prototype=Object.create(null);Object.defineProperty(f.prototype,'__deka_struct',{value:id,enumerable:false,writable:false,configurable:false});f.prototype.constructor=f;return f;}

const GreetingProps = __deka_struct("GreetingProps");
export function Greeting(props) {
return jsx(Fragment, {}, jsxs("stack", {"data-deka-id": "Component:Greeting/i0/i0"}, [jsx("text", {"data-deka-id": "Component:Greeting/i0/i0/i0"}, "Hello from DekaScript"), jsx("text", {"data-deka-id": "Component:Greeting/i0/i0/i1"}, live(function() { return props.message; }))]));
}