use crate::{ImportDecl, ImportSpec, SourceModuleMeta};
use php_rs::parser::ast::{
    BinaryOp, ClassKind, ClassMember, ExportItem, Expr, ExprId, JsxChild, ObjectKey, Program,
    Receiver, Stmt, StmtId, Type as AstType, UnaryOp,
};
use std::collections::{HashMap, HashSet};

#[derive(Clone, Debug)]
struct EnumCaseDef {
    name: String,
    params: Vec<String>,
}

/// A DekaScript method registered on a `deka.Struct` factory.
#[derive(Clone, Debug)]
struct DsMethod {
    name: String,
    body: String,
    is_mut: bool,
}

/// Metadata for a DekaScript struct field, used to supply automatic defaults
/// for empty embedded structs. Optional fields are omitted from the emitted
/// literal and treated as None by the runtime.
#[derive(Clone, Debug)]
struct DsStructField {
    name: String,
    optional: bool,
    empty_embed: bool,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum JsValueKind {
    Array,
    Object,
    String,
}

enum AssignmentTarget {
    Direct(String),
    Append(String),
}

pub(crate) struct JsSubsetEmitter<'a> {
    source: &'a [u8],
    body: String,
    main_body: String,
    uses_jsx_runtime: bool,
    uses_include_stub: bool,
    scopes: Vec<HashSet<String>>,
    immutable_scopes: Vec<HashSet<String>>,
    /// Scope depth at which we entered the current function body.
    /// Variables first assigned inside a function should use `let`, not bare
    /// assignment, even if the name exists in an outer (module-level) scope —
    /// because in PHP, $var inside a function is always a NEW local, shadowing
    /// any outer binding.  We track this so `is_declared_in_function` only looks
    /// at scopes since the function entry.
    function_scope_entry: Vec<usize>,
    /// Variables that were `let`-declared inside a block scope that has since
    /// been popped.  When a variable reference hits this set (but is NOT in any
    /// live scope), the transpiler emits a warning: the variable was block-
    /// scoped and is no longer visible under JS scoping rules.
    popped_declarations: HashSet<String>,
    pub(crate) warnings: Vec<String>,
    meta: SourceModuleMeta,
    struct_schemas: Vec<(String, String)>,
    struct_names: HashSet<String>,
    enum_names: HashSet<String>,
    struct_methods: HashMap<String, Vec<(String, String)>>,
    enum_cases: HashMap<String, Vec<EnumCaseDef>>,
    /// DekaScript struct methods (own body methods + promoted embedded methods)
    /// keyed by struct name. Emitted after all struct factories.
    ds_struct_methods: HashMap<String, Vec<DsMethod>>,
    /// DekaScript receiver methods (`fn (p Person) ...`) keyed by struct name.
    /// These are emitted one at a time so the `deka.Struct` helper wraps them
    /// with the receiver binding.
    ds_receiver_methods: HashMap<String, Vec<DsMethod>>,
    /// Direct embeds for each DekaScript struct, used to promote embedded methods.
    struct_embeds: HashMap<String, Vec<String>>,
    /// DekaScript struct field metadata, used to emit automatic zero values for
    /// empty embedded structs.
    struct_fields: HashMap<String, Vec<DsStructField>>,
    value_kinds: HashMap<String, JsValueKind>,
    /// DekaScript struct/freeze helpers needed by this module. Populated during
    /// AST traversal so the compact prelude only includes them when used.
    uses_deka_struct_helpers: bool,
    uses_deka_freeze: bool,
}

mod assignment;
mod builtins;
mod expr;
mod jsx;
mod names;
mod program;
mod schema;
mod scope;

impl<'a> JsSubsetEmitter<'a> {
    pub(crate) fn new(source: &'a [u8], meta: SourceModuleMeta) -> Self {
        Self {
            source,
            body: String::new(),
            main_body: String::new(),
            uses_jsx_runtime: false,
            uses_include_stub: false,
            function_scope_entry: Vec::new(),
            scopes: vec![HashSet::new()],
            immutable_scopes: vec![HashSet::new()],
            popped_declarations: HashSet::new(),
            warnings: Vec::new(),
            meta,
            struct_schemas: Vec::new(),
            struct_names: HashSet::new(),
            enum_names: HashSet::new(),
            struct_methods: HashMap::new(),
            enum_cases: HashMap::new(),
            ds_struct_methods: HashMap::new(),
            ds_receiver_methods: HashMap::new(),
            struct_embeds: HashMap::new(),
            struct_fields: HashMap::new(),
            value_kinds: HashMap::new(),
            uses_deka_struct_helpers: false,
            uses_deka_freeze: false,
        }
    }

    // ======================================================================
    // DekaScript JS emitter finish()
    //
    // Emits the DS runtime prelude (RFD 21), import/export headers, and the
    // compiled user code. PHPX globalThis helpers have been removed.
    // ======================================================================
    pub(crate) fn finish(self) -> String {
        let mut out = String::new();
        out.push_str("// Generated by deka build. Do not edit manually.\n");
        out.push_str("// Target semantics: JavaScript runtime semantics.\n");
        if self.meta.project_mode {
            out.push_str("const phpxBuildMode = \"subset-ast\";\n");
            out.push_str("const phpxTargetSemantics = \"js\";\n\n");
        } else {
            out.push_str("export const phpxBuildMode = \"subset-ast\";\n");
            out.push_str("export const phpxTargetSemantics = \"js\";\n\n");
        }

        // --- DekaScript runtime prelude (RFD 21) ---
        //
        // DS code runs in a hijacked realm: a curated set of safe globals are
        // wrapped to return errors-as-values, and every other platform API must
        // be reached through the explicit `unsafe` escape hatch. The prelude
        // installs `globalThis.deka` (host helpers including `deka.unsafe`) and
        // `globalThis.unsafe` (pristine host snapshot). RFD 21: no demand-driven
        // wrappers on globalThis.fetch/JSON — those are modules.
        let program_text = format!("{}\n{}", self.body, self.main_body);
        if self.meta.is_ds {
            // Compact prelude: keep generated output small (RFD 13 budget gate)
            // while still capturing all unsafe-only platform APIs and
            // installing the deka host helper.
            out.push_str("const __DekaUnsafeGlobals=(()=>{const g=typeof globalThis!=='undefined'?globalThis:(typeof self!=='undefined'?self:this);return{fetch:g.fetch,JSON:{parse:g.JSON.parse.bind(g.JSON),stringify:g.JSON.stringify.bind(g.JSON)},URL:g.URL,URLSearchParams:g.URLSearchParams,TextEncoder:g.TextEncoder,TextDecoder:g.TextDecoder,Blob:g.Blob,FormData:g.FormData,Headers:g.Headers,Request:g.Request,Response:g.Response,WebSocket:g.WebSocket,crypto:g.crypto,atob:g.atob,btoa:g.btoa,structuredClone:g.structuredClone,queueMicrotask:g.queueMicrotask,setTimeout:g.setTimeout,setInterval:g.setInterval,clearTimeout:g.clearTimeout,clearInterval:g.clearInterval};})();\n");
            let mut deka_entries: Vec<String> = vec![
                "unsafe:(tryFn,catchFn,finallyFn)=>{try{return tryFn();}catch(err){if(catchFn)return catchFn(err);return{__error:err};}finally{if(finallyFn)finallyFn();}}".to_string(),
                "panic:(msg)=>{throw new Error(String(msg));}".to_string(),
            ];
            if self.uses_deka_struct_helpers || self.uses_deka_freeze {
                deka_entries.push("MutationError:class extends Error{constructor(m){super(m);this.name='MutationError';}}".to_string());
            }
            if self.uses_deka_struct_helpers {
                deka_entries.push("Struct:(id)=>{function f(fields){const o=Object.create(f.prototype);Object.assign(o,fields);Object.defineProperty(o,'__deka_struct',{value:id,enumerable:false,writable:false,configurable:false});return o;}f.id=id;Object.defineProperty(f,'name',{value:id,configurable:true});f.prototype=Object.create(null);f.prototype.constructor=f;f.impl=(a,b)=>{if(typeof a==='string'){const k=a;f.prototype[k]=function(...x){return b(this,...x);};}else{for(const k in a)f.prototype[k]=a[k];}return f;};f.implMut=(a,b)=>{if(typeof a==='string'){const k=a;f.prototype[k]=function(...x){if(Object.isFrozen(this))throw new __deka.MutationError(`cannot call mutable method '${k}' on immutable ${id}`);return b(this,...x);};}else{for(const k in a){const fn=a[k];f.prototype[k]=function(...x){if(Object.isFrozen(this))throw new __deka.MutationError(`cannot call mutable method '${k}' on immutable ${id}`);return fn.apply(this,x);};}}return f;};return f;}".to_string());
                deka_entries.push("isStruct:(v,f)=>Boolean(v&&typeof v==='object'&&v.__deka_struct&&(f?v.__deka_struct===f.id:true))".to_string());
                deka_entries.push("getStructId:(v)=>v?.__deka_struct".to_string());
                deka_entries.push("clone:(v)=>structuredClone(v)".to_string());
            }
            if self.uses_deka_freeze {
                deka_entries.push("freeze:(v)=>{if(v===null||typeof v!=='object'||Object.isFrozen(v))return v;if(Array.isArray(v)){for(const x of v)__deka.freeze(x);return Object.freeze(v);}for(const k of Object.keys(v))__deka.freeze(v[k]);return Object.freeze(v);}".to_string());
            }
            if self.uses_jsx_runtime {
                out.push_str("function __DekaRenderJsxChildren(c){if(c==null)return\"\";if(typeof c===\"string\"||typeof c===\"number\")return String(c);if(Array.isArray(c))return c.map(__DekaRenderJsxChildren).join(\"\");return String(c??\"\");}\n");
                deka_entries.push("ui:{Fragment:Symbol.for(\"deka.ui.Fragment\"),jsx:(t,p)=>{p=p??{};if(t===__deka.ui.Fragment)return __DekaRenderJsxChildren(p.children);if(typeof t===\"function\")return String(t(p)??\"\");const{children,...a}=p;const attrs=Object.entries(a).map(([k,v])=>{if(v===true)return` ${k}`;if(v===false||v==null)return\"\";return` ${k}=\"${String(v).replace(/&/g,\"&amp;\").replace(/\"/g,\"&quot;\")}\"`;}).join(\"\");const ch=__DekaRenderJsxChildren(children);return ch===\"\"?`<${t}${attrs} />`:`<${t}${attrs}>${ch}</${t}>`;},jsxs:(t,p)=>__deka.ui.jsx(t,p)}".to_string());
            }
            out.push_str(&format!("const __deka={{ {} }};\n", deka_entries.join(",")));
            out.push_str("const deka=globalThis.deka={...globalThis.deka,...__deka,ui:{...globalThis.deka?.ui,...__deka.ui}};globalThis.unsafe??=__DekaUnsafeGlobals;\n");
            // Language globals — not host dispatchers. `panic` is the DS
            // builtin; `crypto` is WebCrypto, polyfilled only when the isolate
            // did not already provide it.
            if body_refs_global(&program_text, "panic") {
                out.push_str("globalThis.panic??=__deka.panic;\n");
            }
            if body_refs_global(&program_text, "crypto") {
                // Workers expose `crypto` as a getter-only host object. Never
                // replace it; add randomUUID on the existing object when missing.
                out.push_str("(function(){const c=globalThis.crypto;const fill=(b)=>{for(let i=0;i<b.length;i++)b[i]=(Math.random()*256)|0;};const rand=(b)=>{if(c&&typeof c.getRandomValues===\"function\")c.getRandomValues(b);else fill(b);};const uuid=()=>{const b=new Uint8Array(16);rand(b);b[6]=(b[6]&0x0f)|0x40;b[8]=(b[8]&0x3f)|0x80;const h=Array.from(b,x=>x.toString(16).padStart(2,\"0\")).join(\"\");return`${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`;};if(c&&typeof c.randomUUID===\"function\")return;if(c){try{Object.defineProperty(c,\"randomUUID\",{value:uuid,configurable:true});}catch(_){ }return;}globalThis.crypto={getRandomValues:(a)=>{rand(new Uint8Array(a.buffer,a.byteOffset,a.byteLength));return a;},randomUUID:uuid};})();\n");
            }

            // RFD 21: do not wrap fetch/JSON/URL/console on globalThis.
            // DS-safe APIs are modules (`@deka/json`). `unsafe { }` sees the
            // real host via the Proxy; throws become Result at the IIFE.
            out.push('\n');
        }

        let mut imports = self.meta.imports.clone();
        let host_imports: Vec<ImportDecl> = imports
            .iter()
            .filter(|decl| decl.from.trim() == "host")
            .cloned()
            .collect();
        imports.retain(|decl| decl.from.trim() != "host");
        if !host_imports.is_empty() {
            let case = if self.meta.host_is_browser {
                "Browser"
            } else {
                "Native"
            };
            out.push_str("const HostRuntime=Object.freeze({Native:Object.freeze({__enum:\"HostRuntime\",__case:\"Native\",name:\"Native\"}),Browser:Object.freeze({__enum:\"HostRuntime\",__case:\"Browser\",name:\"Browser\"})});\n");
            out.push_str(&format!(
                "const runtime=HostRuntime.{case};\n"
            ));
            out.push_str("function select(cases){const k=runtime.__case===\"Native\"?\"native\":\"browser\";if(cases&&Object.prototype.hasOwnProperty.call(cases,k))return cases[k];return undefined;}\n");
            for decl in &host_imports {
                for spec in &decl.specs {
                    if spec.imported == "runtime" && spec.local != "runtime" {
                        out.push_str(&format!("const {}=runtime;\n", spec.local));
                    }
                    if spec.imported == "select" && spec.local != "select" {
                        out.push_str(&format!("const {}=select;\n", spec.local));
                    }
                    if spec.imported == "HostRuntime" && spec.local != "HostRuntime" {
                        out.push_str(&format!("const {}=HostRuntime;\n", spec.local));
                    }
                }
            }
            out.push('\n');
        }

        // JSX runtime — emits `deka.ui.jsx`, `deka.ui.jsxs`, and `deka.ui.Fragment`
        // calls directly. The host/runtime is responsible for providing the
        // `deka.ui` namespace (see issue #146 / RFD 24). No import is injected here.

        if self.meta.project_mode {
            for decl in &imports {
                if decl.specs.is_empty() {
                    out.push_str(&format!("__dekaRequire({});\n", json_string(&decl.from)));
                    continue;
                }
                out.push_str("const { ");
                for (idx, spec) in decl.specs.iter().enumerate() {
                    if idx > 0 {
                        out.push_str(", ");
                    }
                    if spec.imported == spec.local {
                        out.push_str(&spec.local);
                    } else {
                        out.push_str(&format!("{}: {}", spec.imported, spec.local));
                    }
                }
                out.push_str(&format!(" }} = __dekaRequire({});\n", json_string(&decl.from)));
            }
        } else {
            for decl in &imports {
                if decl.specs.is_empty() {
                    out.push_str(&format!("import '{}';\n", decl.from));
                    continue;
                }
                out.push_str("import { ");
                for (idx, spec) in decl.specs.iter().enumerate() {
                    if idx > 0 {
                        out.push_str(", ");
                    }
                    if spec.imported == spec.local {
                        out.push_str(&spec.local);
                    } else {
                        out.push_str(&format!("{} as {}", spec.imported, spec.local));
                    }
                }
                out.push_str(&format!(" }} from '{}';\n", decl.from));
            }
        }

        if !imports.is_empty() {
            out.push('\n');
        }

        if self.uses_include_stub {
            out.push_str("function __deka_include(path, kind) {\n");
            out.push_str("  throw new Error(`include/require not supported in JS subset emitter: ${kind} ${path}`);\n");
            out.push_str("}\n\n");
        }

        // PHPX/enum struct literals still look up methods from
        // `globalThis.__dekaStructMethods` (see expr.rs's StructLiteral handling).
        // DekaScript structs use `deka.Struct` factories and `Type.impl`/`implMut`,
        // so this registry is only emitted for PHPX/enum paths.
        if !self.struct_methods.is_empty() {
            out.push_str("globalThis.__dekaStructMethods ??= Object.create(null);\n");
        }
        if !self.struct_methods.is_empty() {
            for (name, methods) in &self.struct_methods {
                out.push_str(&format!(
                    "globalThis.__dekaStructMethods[{}] = {{ {} }};\n",
                    json_string(name),
                    methods
                        .iter()
                        .map(|(method_name, body)| format!("{}: {}", method_name, body))
                        .collect::<Vec<_>>()
                        .join(", ")
                ));
            }
            out.push('\n');
        }

        out.push_str("// --- deka:user-code ---\n");
        out.push_str(&self.body);

        if !self.main_body.is_empty() {
            out.push('\n');
            // Top-level statements only need the async IIFE when they actually
            // await something. Emitting it unconditionally turned a two-line
            // program into a wrapped closure for no reason, which is most of
            // what the tour's RAW tab was showing. Note the wrapper was never
            // what enabled await either -- it emits `await __deka_main()` at
            // top level, so the module already had to support top-level await.
            if body_uses_await(&self.main_body) {
                out.push_str("const __deka_main = async () => {\n");
                out.push_str(&self.main_body);
                out.push_str("};\n");
                out.push_str("await __deka_main();\n");
            } else {
                out.push_str(&self.main_body);
            }
        }

        if !self.meta.export_specs.is_empty() {
            out.push('\n');
            if self.meta.project_mode {
                for spec in &self.meta.export_specs {
                    if spec.imported == spec.local {
                        out.push_str(&format!("exports.{} = {};\n", spec.local, spec.local));
                    } else {
                        out.push_str(&format!(
                            "exports.{} = {};\n",
                            spec.imported, spec.local
                        ));
                    }
                }
            } else {
                out.push_str("export { ");
                for (idx, spec) in self.meta.export_specs.iter().enumerate() {
                    if idx > 0 {
                        out.push_str(", ");
                    }
                    if spec.imported == spec.local {
                        out.push_str(&spec.local);
                    } else {
                        out.push_str(&format!("{} as {}", spec.local, spec.imported));
                    }
                }
                out.push_str(" };\n");
            }
        }

        out
    }
}

fn unescape_php_single(raw: &str) -> String {
    let mut out = String::with_capacity(raw.len());
    let mut chars = raw.chars();
    while let Some(ch) = chars.next() {
        if ch == '\\' {
            match chars.next() {
                Some('\'') => out.push('\''),
                Some('\\') => out.push('\\'),
                Some(other) => {
                    out.push('\\');
                    out.push(other);
                }
                None => out.push('\\'),
            }
        } else {
            out.push(ch);
        }
    }
    out
}

fn unescape_php_double(raw: &str) -> String {
    let mut out = String::with_capacity(raw.len());
    let mut chars = raw.chars().peekable();
    while let Some(ch) = chars.next() {
        if ch != '\\' {
            out.push(ch);
            continue;
        }
        let Some(next) = chars.next() else {
            out.push('\\');
            break;
        };
        match next {
            'n' => out.push('\n'),
            'r' => out.push('\r'),
            't' => out.push('\t'),
            'v' => out.push('\x0b'),
            'e' => out.push('\x1b'),
            'f' => out.push('\x0c'),
            '"' => out.push('"'),
            '\\' => out.push('\\'),
            '$' => out.push('$'),
            'x' => {
                let mut hex = String::new();
                for _ in 0..2 {
                    if let Some(h) = chars.peek().copied() {
                        if h.is_ascii_hexdigit() {
                            hex.push(h);
                            chars.next();
                        }
                    }
                }
                if hex.is_empty() {
                    out.push('x');
                } else if let Ok(code) = u8::from_str_radix(&hex, 16) {
                    out.push(code as char);
                }
            }
            '0'..='7' => {
                let mut oct = String::new();
                oct.push(next);
                for _ in 0..2 {
                    if let Some(o) = chars.peek().copied() {
                        if o >= '0' && o <= '7' {
                            oct.push(o);
                            chars.next();
                        } else {
                            break;
                        }
                    }
                }
                if let Ok(code) = u32::from_str_radix(&oct, 8) {
                    if let Some(c) = std::char::from_u32(code) {
                        out.push(c);
                    }
                }
            }
            other => {
                out.push(other);
            }
        }
    }
    out
}

/// True if the emitted top-level body actually awaits something, as a whole
/// word rather than a substring (so `awaited` or `myawait` do not count).
/// Decides whether the `__deka_main` async wrapper is worth emitting at all.
fn body_uses_await(text: &str) -> bool {
    let bytes = text.as_bytes();
    let mut start = 0;
    while let Some(pos) = text[start..].find("await") {
        let idx = start + pos;
        let before_ok = idx == 0
            || !(bytes[idx - 1].is_ascii_alphanumeric()
                || bytes[idx - 1] == b'_'
                || bytes[idx - 1] == b'.');
        let after = idx + "await".len();
        let after_ok =
            after >= bytes.len() || !(bytes[after].is_ascii_alphanumeric() || bytes[after] == b'_');
        if before_ok && after_ok {
            return true;
        }
        start = idx + 1;
    }
    false
}

/// True if `text` (the already-emitted program body) references `name` as a
/// whole identifier, either as `globalThis.<name>` or as a bare identifier.
/// The bare form is accepted so that undeclared user identifiers (which now
/// emit without the `globalThis.` prefix) still trigger demand-driven helper
/// inclusion. Boundaries prevent substring false-positives.
fn body_refs_global(text: &str, name: &str) -> bool {
    let qualified = format!("globalThis.{}", name);
    let bytes = text.as_bytes();
    let mut start = 0;
    while let Some(pos) = text[start..].find(qualified.as_str()) {
        let idx = start + pos;
        let after = idx + qualified.len();
        let boundary_ok =
            after >= bytes.len() || !(bytes[after].is_ascii_alphanumeric() || bytes[after] == b'_');
        if boundary_ok {
            return true;
        }
        start = idx + 1;
    }
    // Bare reference: whole-word match, not preceded by `.` (which would make
    // it a property access on something else) and not followed by an
    // identifier continuation.
    let mut start = 0;
    let name_bytes = name.as_bytes();
    while let Some(pos) = text[start..].find(name) {
        let idx = start + pos;
        let before_ok = idx == 0
            || !(bytes[idx - 1].is_ascii_alphanumeric()
                || bytes[idx - 1] == b'_'
                || bytes[idx - 1] == b'.');
        let after = idx + name_bytes.len();
        let after_ok =
            after >= bytes.len() || !(bytes[after].is_ascii_alphanumeric() || bytes[after] == b'_');
        if before_ok && after_ok {
            return true;
        }
        start = idx + 1;
    }
    false
}

fn add_or_merge_import(imports: &mut Vec<ImportDecl>, from: &str, specs: Vec<ImportSpec>) {
    if let Some(existing) = imports.iter_mut().find(|decl| decl.from == from) {
        for spec in specs {
            if !existing
                .specs
                .iter()
                .any(|item| item.imported == spec.imported && item.local == spec.local)
            {
                existing.specs.push(spec);
            }
        }
        return;
    }
    imports.push(ImportDecl {
        from: from.to_string(),
        specs,
    });
}

fn json_string(input: &str) -> String {
    serde_json::to_string(input).unwrap_or_else(|_| "\"\"".to_string())
}

/// Decode a PHPX string-literal key as it appears in object literal syntax.
///
/// The lexer hands us the full source span for string-literal keys, which
/// includes the surrounding `'` or `"` delimiters. To produce the correct
/// JS object key we need to strip those delimiters and interpret the common
/// escape sequences. Mirrors `parse_string_key` / `unescape_string_key`
/// in `crates/php-rs/src/phpx/typeck/check.rs`.
// Keep in sync with `decode_string_key` in
// runtime/crates/deka_lsp/src/lib.rs and `parse_string_key` in
// runtime/crates/php-rs/src/phpx/typeck/check.rs. All three strip the matching
// quote pair and decode the same escape set on ObjectKey::String tokens.
fn decode_string_key(raw: &str) -> String {
    if raw.len() >= 2 {
        let bytes = raw.as_bytes();
        let first = bytes[0];
        let last = bytes[bytes.len() - 1];
        if (first == b'"' && last == b'"') || (first == b'\'' && last == b'\'') {
            let inner = &raw[1..raw.len() - 1];
            return unescape_string_key(inner, first == b'"');
        }
    }
    raw.to_string()
}

fn unescape_string_key(value: &str, double_quoted: bool) -> String {
    let mut out = String::new();
    let mut chars = value.chars();
    while let Some(ch) = chars.next() {
        if ch != '\\' {
            out.push(ch);
            continue;
        }
        let Some(next) = chars.next() else {
            out.push('\\');
            break;
        };
        match next {
            '\'' if !double_quoted => out.push('\''),
            '"' if double_quoted => out.push('"'),
            '\\' => out.push('\\'),
            'n' if double_quoted => out.push('\n'),
            'r' if double_quoted => out.push('\r'),
            't' if double_quoted => out.push('\t'),
            other => {
                out.push('\\');
                out.push(other);
            }
        }
    }
    out
}

fn is_js_reserved_word(name: &str) -> bool {
    matches!(
        name,
        "await"
            | "break"
            | "case"
            | "catch"
            | "class"
            | "const"
            | "continue"
            | "debugger"
            | "default"
            | "delete"
            | "do"
            | "else"
            | "enum"
            | "export"
            | "extends"
            | "false"
            | "finally"
            | "for"
            | "function"
            | "if"
            | "implements"
            | "import"
            | "in"
            | "instanceof"
            | "interface"
            | "let"
            | "new"
            | "null"
            | "package"
            | "private"
            | "protected"
            | "public"
            | "return"
            | "static"
            | "super"
            | "switch"
            | "this"
            | "throw"
            | "true"
            | "try"
            | "typeof"
            | "var"
            | "void"
            | "while"
            | "with"
            | "yield"
    )
}
