// Generated by dsc transpile. Do not edit manually.
"use strict";
import { jsx } from "./jsx.js";

function withoutChildren(props) {
let __deka_match_result_1;
const __deka_match_scrutinee_1 = ((function() { try { return ((value) => ({ __enum: "Result", __case: "Ok", name: "Ok", value }))((function() { return (
(() => { const { children, ...attributes } = props; return attributes; })()
); })()); } catch (err) { return ((error) => ({ __enum: "Result", __case: "Err", name: "Err", error }))(err instanceof Error ? err : new Error(String(err))); } })());
if (__deka_match_scrutinee_1.__case === "Ok") {
 const v = __deka_match_scrutinee_1.value;
 __deka_match_result_1 = v;
}
else if (__deka_match_scrutinee_1.__case === "Err") {
 __deka_match_result_1 = props;
}
else { throw new Error("non-exhaustive match"); }
return __deka_match_result_1;
}
function propsChildren(props) {
let __deka_match_result_2;
const __deka_match_scrutinee_2 = ((function() { try { return ((value) => ({ __enum: "Result", __case: "Ok", name: "Ok", value }))((function() { return (
Object.hasOwn(props, "children") ? props.children : undefined
); })()); } catch (err) { return ((error) => ({ __enum: "Result", __case: "Err", name: "Err", error }))(err instanceof Error ? err : new Error(String(err))); } })());
if (__deka_match_scrutinee_2.__case === "Ok") {
 const v = __deka_match_scrutinee_2.value;
 __deka_match_result_2 = v;
}
else if (__deka_match_scrutinee_2.__case === "Err") {
 __deka_match_result_2 = Option.None;
}
else { throw new Error("non-exhaustive match"); }
return __deka_match_result_2;
}
function propsRequired() {
return propsRequired();
}
function isNullProps(props) {
let __deka_match_result_3;
const __deka_match_scrutinee_3 = ((function() { try { return ((value) => ({ __enum: "Result", __case: "Ok", name: "Ok", value }))((function() { return (
props == null
); })()); } catch (err) { return ((error) => ({ __enum: "Result", __case: "Err", name: "Err", error }))(err instanceof Error ? err : new Error(String(err))); } })());
if (__deka_match_scrutinee_3.__case === "Ok") {
 const b = __deka_match_scrutinee_3.value;
 __deka_match_result_3 = b;
}
else if (__deka_match_scrutinee_3.__case === "Err") {
 __deka_match_result_3 = false;
}
else { throw new Error("non-exhaustive match"); }
return __deka_match_result_3;
}
export function Form(props = {}) {
if (isNullProps(props)) {
return propsRequired();
}
const children = propsChildren(props);
const attributes = withoutChildren(props);
return jsx("form", attributes, children);
}