// Generated by dsc transpile. Do not edit manually.
"use strict";
const Result = Object.freeze({
  Ok: (value) => ({ __enum: "Result", __case: "Ok", name: "Ok", value }),
  Err: (error) => ({ __enum: "Result", __case: "Err", name: "Err", error })
});
const Option = Object.freeze({
  Some: (value) => ({ __enum: "Option", __case: "Some", name: "Some", value }),
  None: ({ __enum: "Option", __case: "None", name: "None" })
});
const Ok = Result.Ok;
const Err = Result.Err;
const Some = Option.Some;
const None = Option.None;
function kindOf(value) {
let __deka_match_result_1;
const __deka_match_scrutinee_1 = ((function() { try { return ((value) => ({ __enum: "Result", __case: "Ok", name: "Ok", value }))((function() { return (
value == null ? 0 : (value === true || value === false) ? 1 : (Array.isArray(value) ? 2 : 3)
); })()); } catch (err) { return ((error) => ({ __enum: "Result", __case: "Err", name: "Err", error }))(err instanceof Error ? err : new Error(String(err))); } })());
if (__deka_match_scrutinee_1.__case === "Ok") {
 const v = __deka_match_scrutinee_1.value;
 __deka_match_result_1 = v;
}
else if (__deka_match_scrutinee_1.__case === "Err") {
 __deka_match_result_1 = 3;
}
else { throw new Error("non-exhaustive match"); }
return __deka_match_result_1;
}
function asArray(value) {
let __deka_match_result_2;
const __deka_match_scrutinee_2 = ((function() { try { return ((value) => ({ __enum: "Result", __case: "Ok", name: "Ok", value }))((function() { return (
value
); })()); } catch (err) { return ((error) => ({ __enum: "Result", __case: "Err", name: "Err", error }))(err instanceof Error ? err : new Error(String(err))); } })());
if (__deka_match_scrutinee_2.__case === "Ok") {
 const v = __deka_match_scrutinee_2.value;
 __deka_match_result_2 = v;
}
else if (__deka_match_scrutinee_2.__case === "Err") {
 __deka_match_result_2 = [];
}
else { throw new Error("non-exhaustive match"); }
return __deka_match_result_2;
}
function hasOwn(value, key) {
let __deka_match_result_3;
const __deka_match_scrutinee_3 = ((function() { try { return ((value) => ({ __enum: "Result", __case: "Ok", name: "Ok", value }))((function() { return (
value != null && Object.hasOwn(value, key)
); })()); } catch (err) { return ((error) => ({ __enum: "Result", __case: "Err", name: "Err", error }))(err instanceof Error ? err : new Error(String(err))); } })());
if (__deka_match_scrutinee_3.__case === "Ok") {
 const b = __deka_match_scrutinee_3.value;
 __deka_match_result_3 = b;
}
else if (__deka_match_scrutinee_3.__case === "Err") {
 __deka_match_result_3 = false;
}
else { throw new Error("non-exhaustive match"); }
return __deka_match_result_3;
}
function readKey(value, key) {
let __deka_match_result_4;
const __deka_match_scrutinee_4 = ((function() { try { return ((value) => ({ __enum: "Result", __case: "Ok", name: "Ok", value }))((function() { return (
value[key]
); })()); } catch (err) { return ((error) => ({ __enum: "Result", __case: "Err", name: "Err", error }))(err instanceof Error ? err : new Error(String(err))); } })());
if (__deka_match_scrutinee_4.__case === "Ok") {
 const v = __deka_match_scrutinee_4.value;
 __deka_match_result_4 = v;
}
else if (__deka_match_scrutinee_4.__case === "Err") {
 __deka_match_result_4 = value;
}
else { throw new Error("non-exhaustive match"); }
return __deka_match_result_4;
}
function stripKey(value, key) {
let __deka_match_result_5;
const __deka_match_scrutinee_5 = ((function() { try { return ((value) => ({ __enum: "Result", __case: "Ok", name: "Ok", value }))((function() { return (
(() => { const { [key]: _omitted, ...rest } = value; return rest; })()
); })()); } catch (err) { return ((error) => ({ __enum: "Result", __case: "Err", name: "Err", error }))(err instanceof Error ? err : new Error(String(err))); } })());
if (__deka_match_scrutinee_5.__case === "Ok") {
 const v = __deka_match_scrutinee_5.value;
 __deka_match_result_5 = v;
}
else if (__deka_match_scrutinee_5.__case === "Err") {
 __deka_match_result_5 = value;
}
else { throw new Error("non-exhaustive match"); }
return __deka_match_result_5;
}
function isNoneSlot(children) {
let __deka_match_result_6;
const __deka_match_scrutinee_6 = ((function() { try { return ((value) => ({ __enum: "Result", __case: "Ok", name: "Ok", value }))((function() { return (
children === undefined || children.__case === "None"
); })()); } catch (err) { return ((error) => ({ __enum: "Result", __case: "Err", name: "Err", error }))(err instanceof Error ? err : new Error(String(err))); } })());
if (__deka_match_scrutinee_6.__case === "Ok") {
 const b = __deka_match_scrutinee_6.value;
 __deka_match_result_6 = b;
}
else if (__deka_match_scrutinee_6.__case === "Err") {
 __deka_match_result_6 = false;
}
else { throw new Error("non-exhaustive match"); }
return __deka_match_result_6;
}
function someValue(children) {
let __deka_match_result_7;
const __deka_match_scrutinee_7 = ((function() { try { return ((value) => ({ __enum: "Result", __case: "Ok", name: "Ok", value }))((function() { return (
children != null && children.__case === "Some" ? children.value : children
); })()); } catch (err) { return ((error) => ({ __enum: "Result", __case: "Err", name: "Err", error }))(err instanceof Error ? err : new Error(String(err))); } })());
if (__deka_match_scrutinee_7.__case === "Ok") {
 const v = __deka_match_scrutinee_7.value;
 __deka_match_result_7 = v;
}
else if (__deka_match_scrutinee_7.__case === "Err") {
 __deka_match_result_7 = someValue(children);
}
else { throw new Error("non-exhaustive match"); }
return __deka_match_result_7;
}
function fragmentSymbol() {
let __deka_match_result_8;
const __deka_match_scrutinee_8 = ((function() { try { return ((value) => ({ __enum: "Result", __case: "Ok", name: "Ok", value }))((function() { return (
Symbol.for("deka.ui.Fragment")
); })()); } catch (err) { return ((error) => ({ __enum: "Result", __case: "Err", name: "Err", error }))(err instanceof Error ? err : new Error(String(err))); } })());
if (__deka_match_scrutinee_8.__case === "Ok") {
 const v = __deka_match_scrutinee_8.value;
 __deka_match_result_8 = v;
}
else if (__deka_match_scrutinee_8.__case === "Err") {
 __deka_match_result_8 = fragmentSymbol();
}
else { throw new Error("non-exhaustive match"); }
return __deka_match_result_8;
}
export const Fragment = fragmentSymbol();
export function isComponentNode(value) {
let __deka_match_result_9;
const __deka_match_scrutinee_9 = ((function() { try { return ((value) => ({ __enum: "Result", __case: "Ok", name: "Ok", value }))((function() { return (
value != null && typeof value === "object" && value.__componentNode === true
); })()); } catch (err) { return ((error) => ({ __enum: "Result", __case: "Err", name: "Err", error }))(err instanceof Error ? err : new Error(String(err))); } })());
if (__deka_match_scrutinee_9.__case === "Ok") {
 const b = __deka_match_scrutinee_9.value;
 __deka_match_result_9 = b;
}
else if (__deka_match_scrutinee_9.__case === "Err") {
 __deka_match_result_9 = false;
}
else { throw new Error("non-exhaustive match"); }
return __deka_match_result_9;
}
export function normalizeJsxChildren(children) {
const kind = kindOf(children);
if (kind == 0 || kind == 1) {
return [];
}
if (kind != 2) {
let single = [];
single.push(children);
return single;
}
let out = [];
for (const child of asArray(children)) {
const childKind = kindOf(child);
if (childKind != 0 && childKind != 1) {
if (childKind == 2) {
for (const inner of normalizeJsxChildren(child)) {
out.push(inner);
}
} else {
out.push(child);
}
}
}
return out;
}
export function jsx(tag, props, children = Option.None) {
let nodeProps = props;
let normalized = [];
if (isNoneSlot(children)) {
if (hasOwn(props, "children")) {
const nested = readKey(props, "children");
normalized = normalizeJsxChildren(nested);
nodeProps = stripKey(props, "children");
} else {
nodeProps = props;
}
} else {
const value = someValue(children);
if (kindOf(value) == 2) {
let needsNormalize = false;
for (const child of asArray(value)) {
if (kindOf(child) != 3) {
needsNormalize = true;
break;
}
}
if (needsNormalize) {
normalized = normalizeJsxChildren(value);
} else {
normalized = asArray(value);
}
} else {
if (kindOf(value) == 3) {
normalized = [value];
}
}
}
let __deka_match_result_10;
const __deka_match_scrutinee_10 = ((function() { try { return ((value) => ({ __enum: "Result", __case: "Ok", name: "Ok", value }))((function() { return (
({ tag: tag, props: nodeProps, children: normalized, __componentNode: true })
); })()); } catch (err) { return ((error) => ({ __enum: "Result", __case: "Err", name: "Err", error }))(err instanceof Error ? err : new Error(String(err))); } })());
if (__deka_match_scrutinee_10.__case === "Ok") {
 const v = __deka_match_scrutinee_10.value;
 __deka_match_result_10 = v;
}
else if (__deka_match_scrutinee_10.__case === "Err") {
 __deka_match_result_10 = jsx(tag, props, children);
}
else { throw new Error("non-exhaustive match"); }
return __deka_match_result_10;
}
export const jsxs = jsx;
const optionPreludeAnchor = Option.None;