// Generated by dsc transpile. Do not edit manually.
"use strict";




function notFound() {
return {status: 404, body: "Not found", headers: {location: ""}};
}
function requestPath(request) {
let __deka_match_result_1;
const __deka_match_scrutinee_1 = ((function() { try { return ((value) => ({ __enum: "Result", __case: "Ok", name: "Ok", value }))((function() { return (
request && request.pathname === "" ? "/" : (request && request.pathname) || "/"
); })()); } catch (err) { return ((error) => ({ __enum: "Result", __case: "Err", name: "Err", error }))(err instanceof Error ? err : new Error(String(err))); } })());
if (__deka_match_scrutinee_1.__case === "Ok") {
 const v = __deka_match_scrutinee_1.value;
 __deka_match_result_1 = v;
}
else if (__deka_match_scrutinee_1.__case === "Err") {
 __deka_match_result_1 = "/";
}
else { throw new Error("non-exhaustive match"); }
return __deka_match_result_1;
}
function requestMethod(request) {
let __deka_match_result_2;
const __deka_match_scrutinee_2 = ((function() { try { return ((value) => ({ __enum: "Result", __case: "Ok", name: "Ok", value }))((function() { return (
String((request && request.method) || "GET")
); })()); } catch (err) { return ((error) => ({ __enum: "Result", __case: "Err", name: "Err", error }))(err instanceof Error ? err : new Error(String(err))); } })());
if (__deka_match_scrutinee_2.__case === "Ok") {
 const v = __deka_match_scrutinee_2.value;
 __deka_match_result_2 = v;
}
else if (__deka_match_scrutinee_2.__case === "Err") {
 __deka_match_result_2 = "GET";
}
else { throw new Error("non-exhaustive match"); }
return __deka_match_result_2;
}
function trimSlashes(s) {
let __deka_match_result_3;
const __deka_match_scrutinee_3 = ((function() { try { return ((value) => ({ __enum: "Result", __case: "Ok", name: "Ok", value }))((function() { return (
s.replace(/^\/+|\/+$/g, "")
); })()); } catch (err) { return ((error) => ({ __enum: "Result", __case: "Err", name: "Err", error }))(err instanceof Error ? err : new Error(String(err))); } })());
if (__deka_match_scrutinee_3.__case === "Ok") {
 const v = __deka_match_scrutinee_3.value;
 __deka_match_result_3 = v;
}
else if (__deka_match_scrutinee_3.__case === "Err") {
 __deka_match_result_3 = s;
}
else { throw new Error("non-exhaustive match"); }
return __deka_match_result_3;
}
function routeKeys(routes) {
let __deka_match_result_4;
const __deka_match_scrutinee_4 = ((function() { try { return ((value) => ({ __enum: "Result", __case: "Ok", name: "Ok", value }))((function() { return (
Object.keys(routes)
); })()); } catch (err) { return ((error) => ({ __enum: "Result", __case: "Err", name: "Err", error }))(err instanceof Error ? err : new Error(String(err))); } })());
if (__deka_match_scrutinee_4.__case === "Ok") {
 const v = __deka_match_scrutinee_4.value;
 __deka_match_result_4 = v;
}
else if (__deka_match_scrutinee_4.__case === "Err") {
 __deka_match_result_4 = [];
}
else { throw new Error("non-exhaustive match"); }
return __deka_match_result_4;
}
function routeHandlers(routes, route) {
let __deka_match_result_5;
const __deka_match_scrutinee_5 = ((function() { try { return ((value) => ({ __enum: "Result", __case: "Ok", name: "Ok", value }))((function() { return (
routes[route]
); })()); } catch (err) { return ((error) => ({ __enum: "Result", __case: "Err", name: "Err", error }))(err instanceof Error ? err : new Error(String(err))); } })());
if (__deka_match_scrutinee_5.__case === "Ok") {
 const v = __deka_match_scrutinee_5.value;
 __deka_match_result_5 = v;
}
else if (__deka_match_scrutinee_5.__case === "Err") {
 __deka_match_result_5 = routes;
}
else { throw new Error("non-exhaustive match"); }
return __deka_match_result_5;
}
function methodHandler(handlers, method) {
let __deka_match_result_6;
const __deka_match_scrutinee_6 = ((function() { try { return ((value) => ({ __enum: "Result", __case: "Ok", name: "Ok", value }))((function() { return (
handlers[method]
); })()); } catch (err) { return ((error) => ({ __enum: "Result", __case: "Err", name: "Err", error }))(err instanceof Error ? err : new Error(String(err))); } })());
if (__deka_match_scrutinee_6.__case === "Ok") {
 const v = __deka_match_scrutinee_6.value;
 __deka_match_result_6 = v;
}
else if (__deka_match_scrutinee_6.__case === "Err") {
 __deka_match_result_6 = handlers;
}
else { throw new Error("non-exhaustive match"); }
return __deka_match_result_6;
}
function isFunction(value) {
let __deka_match_result_7;
const __deka_match_scrutinee_7 = ((function() { try { return ((value) => ({ __enum: "Result", __case: "Ok", name: "Ok", value }))((function() { return (
typeof value === "function"
); })()); } catch (err) { return ((error) => ({ __enum: "Result", __case: "Err", name: "Err", error }))(err instanceof Error ? err : new Error(String(err))); } })());
if (__deka_match_scrutinee_7.__case === "Ok") {
 const b = __deka_match_scrutinee_7.value;
 __deka_match_result_7 = b;
}
else if (__deka_match_scrutinee_7.__case === "Err") {
 __deka_match_result_7 = false;
}
else { throw new Error("non-exhaustive match"); }
return __deka_match_result_7;
}
function staticPrefix(route) {
let parts = [];
for (const part of trimSlashes(route).split("/")) {
if (part == "") {
continue;
}
if (part.startsWith("[")) {
break;
}
parts.push(part);
}
if (parts.length == 0) {
return "/";
}
return "/" + parts.join("/") + "/";
}
function oneSegmentAfter(path, prefix) {
if (!path.startsWith(prefix)) {
return false;
}
const rest = path.slice(prefix.length, path.length);
if (rest == "" || rest.includes("/")) {
return false;
}
return true;
}
function routeMatches(route, path) {
if (route == path) {
return true;
}
if (!route.includes("[")) {
return false;
}
return oneSegmentAfter(path, staticPrefix(route));
}
function callHandler(handler, request) {
let __deka_match_result_8;
const __deka_match_scrutinee_8 = ((function() { try { return ((value) => ({ __enum: "Result", __case: "Ok", name: "Ok", value }))((function() { return (
handler(request)
); })()); } catch (err) { return ((error) => ({ __enum: "Result", __case: "Err", name: "Err", error }))(err instanceof Error ? err : new Error(String(err))); } })());
if (__deka_match_scrutinee_8.__case === "Ok") {
 const r = __deka_match_scrutinee_8.value;
 __deka_match_result_8 = r;
}
else if (__deka_match_scrutinee_8.__case === "Err") {
 __deka_match_result_8 = OPAQUE_500;
}
else { throw new Error("non-exhaustive match"); }
return __deka_match_result_8;
}
export function runApiRouter(request, routes) {
const path = requestPath(request);
const method = requestMethod(request);
let handlers = routes;
let matched = false;
for (const route of routeKeys(routes)) {
if (routeMatches(route, path)) {
handlers = routeHandlers(routes, route);
matched = true;
break;
}
}
if (!matched) {
return notFound();
}
let handler = methodHandler(handlers, method);
if (!isFunction(handler) && method == "HEAD" && isFunction(methodHandler(handlers, "GET"))) {
handler = methodHandler(handlers, "GET");
}
if (!isFunction(handler)) {
return {status: 405, body: "Method not allowed", headers: {location: ""}};
}
return callHandler(handler, request);
}
const OPAQUE_500 = {status: 500, body: "Internal Server Error", headers: {location: ""}};