[package]
name = "deka-dns"
version = "0.24.3"
edition = "2024"

[dependencies]
axum = { workspace = true }
base64 = "0.22"
bytes = { workspace = true }
nix = { version = "0.30", features = ["socket", "uio", "net"] }
redis = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
simple-dns = "0.9"
tokio = { workspace = true, features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zega-core = { path = "../zega/zega-core" }

[dev-dependencies]
tempfile = "3"
tower = { version = "0.5", features = ["util"] }
