use std::fs;
use std::process::Command;

fn cli_bin() -> &'static str {
    env!("CARGO_BIN_EXE_cli")
}

#[test]
fn transpile_command_emits_adjacent_v8_input() {
    let temp = tempfile::tempdir().expect("tempdir");
    let source = temp.path().join("answer.ds");
    fs::write(&source, "export const answer = 42;\n").expect("source fixture");

    let output = Command::new(cli_bin())
        .arg("transpile")
        .arg(&source)
        .output()
        .expect("run transpile");
    assert!(
        output.status.success(),
        "{}",
        String::from_utf8_lossy(&output.stderr)
    );

    let emitted = fs::read_to_string(source.with_extension("js")).expect("emitted JavaScript");
    assert!(emitted.starts_with("// Generated by deka transpile."));
    assert!(emitted.contains("export { answer };"));
}

#[test]
fn transpile_help_describes_output_modes() {
    let output = Command::new(cli_bin())
        .args(["transpile", "--help"])
        .output()
        .expect("run transpile help");
    assert!(output.status.success());
    let text = format!(
        "{}{}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    for expected in ["--preserve", "--bundle", "--treeshake", "Examples:"] {
        assert!(text.contains(expected), "missing {expected}: {text}");
    }
}
