[package]
name = "gild"
version = "0.1.0"
edition = "2021"

[lib]
name = "gild"
path = "src/lib.rs"

[[bin]]
name = "gild"
path = "src/main.rs"

[dependencies]
age = "0.11.3"
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
futures-util = { workspace = true }
harar-client = { version = "0.2", registry-index = "sparse+https://git.tana.gg/index/" }
libc = "0.2"
rcgen = { version = "0.12", features = ["x509-parser"] }
reqwest = { version = "0.11", default-features = false, features = ["blocking", "json", "rustls-tls", "stream"] }
regex = "1"
rusqlite = { version = "0.32", features = ["bundled"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = "0.10"
time = "0.3"
tokio = { workspace = true, features = ["full"] }
toml = { workspace = true }
x509-parser = "0.16"

[dev-dependencies]
hmac = "0.12"
tempfile = "3"
